package com.hpcai270

val hpcDaysPart3 = listOf(
    Day(11,"NVMe","Fast local storage","NVMe is a storage protocol designed for non-volatile memory, especially flash. It uses PCIe and a highly parallel command model to reduce software overhead and support high I/O concurrency.","STORAGE EVOLUTION\n\nHDD → SATA SSD → SAS SSD → NVMe SSD\n\nAI systems use local NVMe for scratch data, staging, caching and temporary datasets.","Explain why NVMe is a natural fit for high-performance local storage.", pages = listOf(
        "NVMe IN ONE IDEA\n\nNVMe is a protocol designed around modern non-volatile storage. Unlike older storage protocols designed around spinning disks, NVMe was designed to exploit the parallelism and low latency available through PCIe-attached flash devices.",
        "THE DATA PATH\n\nCPU\n ↓\nPCIe\n ↓\nNVMe controller\n ↓\nNAND / flash media\n\nThe controller exposes namespaces and multiple I/O queues. Applications can submit many requests concurrently instead of relying on one narrow command path.",
        "WHY QUEUES MATTER\n\nAI/HPC servers may have many CPU cores and many concurrent workers. NVMe supports multiple submission/completion queues so I/O can be processed in parallel.\n\nThe important lesson: storage performance depends on the whole path, not only the media.",
        "LOCAL NVMe USE CASES\n\n• Scratch space for intermediate data\n• Dataset staging\n• Local cache\n• Temporary training data\n• Checkpoint staging\n• High-performance application working sets\n\nLocal NVMe is fast, but it is not automatically shared storage or durable cluster-wide storage.",
        "TOOLS\n\nLinux: lsblk, nvme, lspci, iostat\nBenchmark: fio\n\nLook at queue depth, block size, read/write pattern and latency. A benchmark must describe the workload or its result is easy to misinterpret.",
        "REAL-WORLD CONNECTION\n\nModern AI servers commonly combine accelerators, large memory, high-speed networking and local NVMe. NVIDIA AI infrastructure architectures also distinguish local compute resources from shared storage and network paths.\n\nINTERVIEW: Why can local NVMe be excellent for scratch but unsuitable as the only copy of a dataset?"
    )),
    Day(12,"NVMe-oF","NVMe over Fabrics","NVMe-oF extends NVMe semantics across a network fabric. A host can access remote NVMe storage rather than using only directly attached devices.","HOST → FABRIC → NVMe TARGET\n\nCommon transport families include NVMe/TCP, NVMe/RDMA and NVMe over Fibre Channel. The fabric introduces network latency, congestion and additional failure domains.","Compare local NVMe with remote NVMe-oF storage.", pages = listOf(
        "WHY NVMe-oF?\n\nLocal NVMe is physically inside or directly attached to a server. NVMe-oF allows NVMe storage resources to be reached over a fabric.\n\nThink:\nLocal → CPU → PCIe → SSD\nRemote → CPU → NIC/HBA → fabric → target → NVMe media",
        "THE COMPONENTS\n\nHOST / INITIATOR → transport network → TARGET / CONTROLLER → NVMe media\n\nThe host discovers remote namespaces and sends NVMe commands through the selected transport.",
        "THREE IMPORTANT TRANSPORTS\n\nNVMe/TCP → uses ordinary IP networking.\nNVMe/RDMA → uses RDMA-capable networking.\nNVMe/FC → carries NVMe through Fibre Channel infrastructure.\n\nEach has different operational and performance characteristics.",
        "LATENCY BUDGET\n\nLocal NVMe avoids the network hop. Remote NVMe adds NIC/HBA processing, switches and fabric traversal.\n\nBut shared NVMe-oF can provide centralized capacity, management and high-performance access to multiple hosts. Architecture is a trade-off, not simply 'local is always better.'",
        "STORAGE-ADMIN CONNECTION\n\nYour SAN knowledge transfers directly into the concept of initiator, target, fabric, zoning/access control and multipathing. The major change is learning NVMe semantics and modern transports.\n\nThis is one bridge from traditional enterprise storage to HPC infrastructure.",
        "INTERVIEW CHECK\n\nQ: Name three NVMe-oF transports.\nQ: What is the main performance cost of remote NVMe?\nQ: Why would an organization still choose remote NVMe?\n\nAnswer using latency, sharing, scalability, centralized management and failure domains."
    )),
    Day(13,"RDMA","Remote Direct Memory Access","RDMA is a networking capability that enables direct data movement between memory regions on different systems while reducing CPU and software overhead for the data path compared with conventional networking models.","APPLICATION / GPU\n ↓\nRDMA stack\n ↓\nNIC / HCA ===== NIC / HCA\n ↓\nREMOTE MEMORY OR STORAGE\n\nInfiniBand and RoCE are major RDMA-capable technologies.","Define RDMA precisely without simply saying 'very fast networking'.", pages = listOf(
        "THE PROBLEM RDMA ADDRESSES\n\nTraditional network I/O can involve significant CPU and kernel/software processing. At massive scale, communication overhead becomes important.\n\nRDMA is designed to move data efficiently between systems while minimizing overhead in appropriate workloads.",
        "A SIMPLE MODEL\n\nHost A memory\n      ↓\n   RDMA NIC\n      ║\n      ║ fabric\n      ║\n   RDMA NIC\n      ↓\nHost B memory\n\nThe NICs perform important parts of the communication work.",
        "KEY TERMS\n\nHCA → Host Channel Adapter, common InfiniBand terminology.\nRNIC → RDMA-capable Ethernet NIC.\nQueue Pair → communication endpoint concept used by RDMA transports.\nVerbs → programming interface used to request RDMA operations.\n\nYou do not need to program RDMA yet; learn the architecture first.",
        "RDMA + STORAGE\n\nRDMA can carry storage traffic as well as application communication. NVMe/RDMA is one example. Parallel filesystems can also use high-performance network paths depending on implementation and deployment.",
        "RDMA + AI\n\nDistributed AI training requires GPUs to exchange information repeatedly. RDMA-capable fabrics can reduce communication overhead and support high-bandwidth GPU-to-GPU or GPU-to-storage data movement architectures.",
        "TROUBLESHOOTING MINDSET\n\nIf RDMA performance is poor, inspect both endpoints and the fabric: link state, negotiated speed, errors, congestion, MTU/configuration, queue behavior and application workload. Never assume the storage array is automatically the problem.\n\nINTERVIEW: Why is CPU overhead important when thousands of endpoints communicate?"
    )),
    Day(14,"InfiniBand & RoCE","The high-speed fabric","InfiniBand is a high-performance fabric widely used in HPC and AI clusters. RoCE carries RDMA over Ethernet, allowing Ethernet-based designs to provide RDMA capabilities when correctly engineered.","GPU SERVER → HCA/NIC → SWITCH → HCA/NIC → GPU SERVER / STORAGE\n\nNVIDIA Quantum InfiniBand and Spectrum Ethernet are examples of current high-performance networking product families.","Connect InfiniBand, RoCE, RDMA, HCA/NIC and switch in one architecture.", pages = listOf(
        "INFINIBAND\n\nInfiniBand is a purpose-built high-performance interconnect used extensively in HPC and AI. It provides a fabric designed for high bandwidth, low latency and RDMA communication.",
        "ROCEv2\n\nRoCE = RDMA over Converged Ethernet. RoCEv2 uses IP networking to carry RDMA traffic over Ethernet.\n\nThis can fit organizations that want Ethernet economics and operations while supporting RDMA workloads, but the network must be engineered for congestion and loss behavior.",
        "FABRIC MENTAL MODEL\n\nGPU node\n  ↓\nHCA / NIC\n  ↓\nLeaf switch\n  ↓\nSpine / fabric\n  ↓\nLeaf switch\n  ↓\nHCA / NIC\n  ↓\nGPU / storage node\n\nScale comes from many parallel links and carefully designed topology.",
        "NVIDIA PRODUCTS TO RECOGNIZE\n\nConnectX → high-performance network adapters.\nQuantum InfiniBand → NVIDIA InfiniBand switch/fabric family.\nSpectrum / Spectrum-X → NVIDIA Ethernet networking for AI-scale environments.\nBlueField → data processing unit family used in infrastructure architectures.\n\nProduct names matter in interviews, but architecture matters more.",
        "WHAT A STORAGE ENGINEER MUST WATCH\n\nStorage may be capable of huge throughput, but the fabric must deliver it. Check link speed, number of paths, oversubscription, congestion, errors, queueing and endpoint configuration.\n\nThis is why modern HPC storage engineers need networking knowledge.",
        "INTERVIEW CHECK\n\nQ: Is RoCE the same thing as RDMA?\nA: No. RDMA is the communication capability/model; RoCE is an Ethernet transport technology for RDMA.\n\nQ: Is InfiniBand Ethernet?\nA: No. It is a distinct fabric technology."
    )),
    Day(15,"The complete HPC-AI data path","Connect everything","AI infrastructure is a coordinated system. Compute, memory, storage and networking must work together. The storage engineer's job is to understand where data moves and where performance can be lost.","DATASET\n ↓\nPARALLEL FILE / OBJECT STORAGE\n ↓\nSTORAGE SERVERS + NVMe\n ↓\nRDMA / INFINIBAND / ROCE\n ↓\nGPU SERVERS\n ↓\nGPU MEMORY\n ↓\nTRAINING\n ↓\nCHECKPOINT → STORAGE","Explain the entire data path in three minutes.", pages = listOf(
        "THE BIG PICTURE\n\nDataset → storage → network → compute → result/checkpoint\n\nHPC adds scale: many compute nodes, many processes, many storage targets and high-speed fabrics operate together.",
        "A TRAINING STEP\n\n1. Workers request batches of data.\n2. Storage serves the dataset.\n3. Network carries data to compute nodes.\n4. Data reaches GPU memory.\n5. GPUs execute tensor operations.\n6. Distributed workers communicate.\n7. Checkpoints are written back to storage.\n\nThis cycle repeats many times.",
        "WHERE CAN IT BREAK?\n\nStorage throughput too low → workers wait.\nMetadata overloaded → file operations stall.\nNetwork congested → communication slows.\nGPU memory pressure → data movement changes.\nCPU bottleneck → accelerator cannot be fed efficiently.\nFilesystem contention → aggregate performance collapses.",
        "THE STORAGE ENGINEER'S NEW ROLE\n\nTraditional question: 'Is the array healthy?'\n\nHPC question: 'Where is the bottleneck in the end-to-end data path?'\n\nYou still need storage health skills, but now you also need Linux, networking, filesystem and application-performance knowledge.",
        "YOUR 15-DAY CHECKPOINT\n\nYou should now be able to explain:\n• HPC and parallelism\n• MPI and OpenMP\n• parallel filesystem basics\n• NVMe and NVMe-oF\n• RDMA\n• InfiniBand and RoCE\n• GPU starvation\n• why storage is part of AI performance\n\nNext section: Linux administration and hands-on performance work.",
        "FINAL INTERVIEW EXERCISE\n\nDraw this without notes:\n\nGPU nodes ↔ high-speed fabric ↔ storage servers ↔ parallel filesystem ↔ dataset\n\nThen point to three places where latency can occur and three places where throughput can become a bottleneck.\n\nIf you can do that clearly, you are starting to think like an HPC infrastructure engineer."
    ))
)
