package com.hpcai270

// Days 73–83: high-performance networking for HPC and AI storage.
val hpcDaysPart9 = listOf(
    Day(73,"HPC networking fundamentals","Bandwidth, latency, topology and congestion",
        "HPC networking connects compute, storage and management systems. For AI, the network can be just as important as the GPUs because distributed jobs exchange data continuously.",
        "DATA PATH\n\nGPU SERVER → NIC/HCA → SWITCH FABRIC → STORAGE NIC → STORAGE SERVER\n\nEvery hop adds latency and every shared link can become a bottleneck.",
        "KEY METRICS\n\nBandwidth = data rate.\nLatency = time per operation/message.\nPacket loss = retransmission/error cost.\nUtilization = how much link capacity is consumed.\nCongestion = demand exceeding available capacity.",
        "AI CONNECTION\n\nTraining jobs may synchronize gradients and read data concurrently. A congested fabric can reduce GPU utilization even when the storage devices themselves are healthy.",
        "INTERVIEW: ‘Why is networking part of storage performance?’ Trace a read from storage media to GPU memory and identify NIC, switch, transport and congestion as possible bottlenecks.",
        "LAB: draw a leaf-spine fabric and mark storage and compute traffic. Identify which links are shared.",
        "YOU SHOULD BE ABLE TO: discuss storage and network as one end-to-end performance path."),
    Day(74,"InfiniBand architecture","HCA, switches and subnet management",
        "InfiniBand is a high-performance interconnect widely used in HPC and AI clusters. It provides low-latency communication and high bandwidth with a specialized fabric architecture.",
        "FABRIC\n\nCOMPUTE HCA → LEAF → SPINE → LEAF → STORAGE HCA\n\nSubnet management configures and manages the fabric so endpoints can communicate.",
        "TERMS\n\nHCA = Host Channel Adapter.\nLID = local identifier assigned in the fabric.\nSubnet Manager = controls fabric routing/configuration.\nPort = physical/logical endpoint.\n\nNVIDIA ConnectX and Quantum families are important ecosystem products.",
        "AI CONNECTION\n\nGPU clusters use InfiniBand for high-speed collective communication. Storage traffic can share or integrate with the same high-performance networking architecture depending on design.",
        "TROUBLESHOOTING\n\nCheck port state, link speed, counters, topology, routing and subnet management. A dead or degraded link can create severe application-level performance symptoms.",
        "LAB: learn to recognize ibstat, iblinkinfo, ibdiagnet and ibtracert concepts in a lab or documented environment. Never run destructive changes on production fabric.",
        "INTERVIEW: explain why an HCA is different from an ordinary Ethernet NIC and why fabric management matters."),
    Day(75,"RDMA","Moving data with less CPU involvement",
        "RDMA allows one host to access memory on another host using specialized networking semantics with reduced CPU and software overhead compared with traditional network I/O paths.",
        "CONCEPT\n\nAPPLICATION → RDMA API → HCA → FABRIC → REMOTE HCA → MEMORY\n\nThe HCA performs much of the data movement.",
        "TERMS\n\nQP = Queue Pair.\nCQ = Completion Queue.\nMR = Memory Region.\nWR = Work Request.\n\nYou should understand the relationship, not merely memorize abbreviations.",
        "STORAGE CONNECTION\n\nRDMA can reduce transport overhead for high-performance storage protocols such as NVMe-oF over RDMA and for filesystem/network traffic where supported.",
        "INTERVIEW: ‘Why does RDMA help AI infrastructure?’ Lower latency and CPU overhead can improve communication efficiency, especially when thousands of endpoints exchange data.",
        "TROUBLESHOOTING: distinguish physical link failure, fabric configuration, RDMA resource/configuration problems and application-level performance issues.",
        "LAB: draw a TCP storage path and an RDMA storage path. Mark where CPU and memory copies can differ."),
    Day(76,"RoCEv2","RDMA over Ethernet",
        "RoCEv2 carries RDMA traffic over IP/Ethernet. It can provide RDMA performance while using an Ethernet fabric, but the network must be engineered carefully for loss and congestion behavior.",
        "PATH\n\nAPPLICATION → RDMA → NIC → ETHERNET/IP FABRIC → REMOTE NIC → MEMORY",
        "CONGESTION\n\nAI fabrics can generate bursty traffic. Packet loss and congestion can severely affect RDMA workloads, so QoS and congestion-control design matter.",
        "PFC + ECN\n\nPFC can provide priority-based flow control. ECN can signal congestion without requiring packet loss. Exact production configuration is architecture-specific.",
        "INTERVIEW: ‘Why is RoCE more than just enabling RDMA on Ethernet?’ Because the fabric must be designed and validated for loss/congestion behavior, QoS, MTU, routing and NIC configuration.",
        "TROUBLESHOOTING: check NIC state, VLAN/DSCP/QoS, MTU consistency, ECN/PFC behavior, switch counters and application latency.",
        "LAB: draw an RDMA over Ethernet path and label where congestion can occur."),
    Day(77,"Ethernet vs InfiniBand","Choosing the fabric",
        "Both Ethernet and InfiniBand can support demanding AI/HPC environments. The choice depends on performance requirements, ecosystem, operations, topology, cost and application design.",
        "COMPARE\n\nETHERNET\n• broad ecosystem\n• IP-based networking\n• RoCE can provide RDMA\n\nINFINIBAND\n• purpose-built HPC fabric\n• specialized management\n• strong low-latency/high-throughput ecosystem",
        "IMPORTANT\n\nDo not answer ‘InfiniBand is always faster’ without defining workload and measurement. Modern Ethernet/RoCE systems can be extremely high performance.",
        "AI CONNECTION\n\nNVIDIA AI infrastructure can use InfiniBand or Ethernet technologies depending on platform architecture. The engineer must understand the data path, not only the brand.",
        "INTERVIEW: ask about endpoint count, bandwidth, latency, congestion tolerance, existing operational expertise, required RDMA, topology and application communication pattern before choosing.",
        "LAB: make a decision matrix for an AI cluster with 256 GPU nodes and justify Ethernet/RoCE versus InfiniBand using measurable requirements.",
        "GOAL: demonstrate architecture judgment."),
    Day(78,"NVMe-oF over RDMA","Fast networked storage",
        "NVMe over Fabrics extends NVMe semantics across a network. RDMA transport can provide a low-overhead path between hosts and NVMe storage.",
        "PATH\n\nAPPLICATION → FILESYSTEM/BLOCK LAYER → NVMe-oF HOST → RDMA → FABRIC → NVMe-oF TARGET → SSD",
        "WHY IT MATTERS\n\nLocal NVMe has very low latency. NVMe-oF attempts to preserve efficient NVMe-style access while allowing storage to be shared across a fabric.",
        "COMPARE\n\nNVMe/TCP uses TCP/IP and is operationally familiar. NVMe/RDMA can reduce latency/CPU overhead where the network and infrastructure support it. NVMe/FC integrates NVMe with Fibre Channel environments.",
        "INTERVIEW: ‘Why not just use NFS?’ Answer depends on workload. NVMe-oF provides block-level semantics and can target very low-latency shared storage, while NFS provides file semantics and namespace convenience.",
        "TROUBLESHOOTING: separate discovery, transport connectivity, subsystem/path state, host multipathing and backend NVMe performance.",
        "LAB: draw NFS, iSCSI and NVMe-oF paths and compare protocol layers and expected latency behavior."),
    Day(79,"Fabric topology","Leaf-spine, oversubscription and locality",
        "Network topology determines how traffic moves and where contention occurs. AI clusters often use leaf-spine architectures to provide predictable east-west connectivity.",
        "TOPOLOGY\n\nGPU LEAF ─┐\nSTORAGE LEAF ─┼→ SPINES\nGPU LEAF ─┘\n\nThe number of uplinks and spine capacity determine aggregate bandwidth and oversubscription.",
        "OVERSUBSCRIPTION\n\nIf access ports offer more aggregate bandwidth than uplinks, the topology is oversubscribed. That may be acceptable for some workloads but dangerous for high-bandwidth synchronized AI traffic.",
        "STORAGE DESIGN\n\nStorage servers with many high-speed NICs need corresponding switch/fabric capacity. One undersized uplink can bottleneck an otherwise powerful storage platform.",
        "INTERVIEW: ‘How would you size the network for AI storage?’ Start from aggregate workload demand, number of clients, per-client bandwidth, concurrency, redundancy and acceptable oversubscription.",
        "LAB: calculate required uplink capacity for 32 storage nodes each capable of 400 Gb/s, then discuss why theoretical capacity is not identical to application throughput.",
        "YOU SHOULD BE ABLE TO: spot a topology bottleneck on a whiteboard."),
    Day(80,"Network troubleshooting toolkit","From cable to application",
        "Senior infrastructure troubleshooting requires a layered network methodology.",
        "LAYERS\n\n1 physical/link\n2 Ethernet/IP\n3 routing\n4 transport\n5 RDMA/fabric\n6 storage protocol\n7 filesystem\n8 application",
        "TOOLS\n\nLinux: ip, ss, ethtool, ping, traceroute/tracepath, iperf3, ss.\nIB: ibstat, iblinkinfo, ibdiagnet, ibtracert where available.\nStorage: fio/ior and vendor telemetry.",
        "METHOD\n\nConfirm link → verify addressing/routes → test throughput/latency → inspect errors/congestion → test protocol → test storage → reproduce application workload.",
        "INTERVIEW: ‘Storage is slow but disks are idle. What next?’ Look at network utilization, packet errors, retransmission, RDMA/fabric health, client CPU and protocol latency.",
        "LAB: create a troubleshooting flowchart that starts with ‘one client slow’ versus ‘all clients slow’.",
        "GOAL: avoid random command execution and move from evidence to hypothesis."),
    Day(81,"QoS and congestion","Why a fast network can still be slow",
        "Quality of Service determines how traffic competes for shared resources. In AI fabrics, storage, collective communication and management traffic can coexist.",
        "CONGESTION PATH\n\nMANY SENDERS → SHARED LINK → QUEUE GROWS → LATENCY / DROPS → APPLICATION SLOWS",
        "KEY IDEAS\n\nTraffic classes, priority, buffering, ECN and flow control can influence behavior. Exact configuration depends on Ethernet or InfiniBand architecture.",
        "AI CONNECTION\n\nSynchronized GPU workloads can create microbursts. A fabric that looks lightly utilized on average can still experience queueing and tail-latency problems.",
        "INTERVIEW: ‘Why does average utilization hide congestion?’ Because bursts and queue occupancy occur on short timescales; average counters can smooth out the event.",
        "LAB: sketch a burst of traffic entering a link slower than the combined senders and show how queueing increases latency.",
        "YOU SHOULD BE ABLE TO: connect QoS concepts to real storage and AI symptoms."),
    Day(82,"NVIDIA networking ecosystem","ConnectX, Spectrum and Quantum",
        "NVIDIA's networking portfolio includes high-speed adapters and switching platforms used across Ethernet and InfiniBand AI infrastructure. For interviews, understand roles rather than memorizing SKU lists.",
        "ROLE MODEL\n\nCONNECTX → endpoint NIC/HCA\nQUANTUM → InfiniBand switching/fabric\nSPECTRUM → Ethernet switching\nUFM → InfiniBand fabric management ecosystem",
        "STORAGE CONNECTION\n\nA high-performance storage server may use ConnectX adapters to connect to an InfiniBand or Ethernet fabric. The storage system's network interfaces become part of its aggregate throughput design.",
        "INTERVIEW: ‘What does the NIC do in an AI storage path?’ It terminates the network connection, moves data between host memory/storage software and the fabric, and may offload communication features depending on technology.",
        "TROUBLESHOOTING: identify endpoint, switch and management roles separately. A NIC problem and a fabric-wide routing problem require different investigation.",
        "LAB: draw GPU server, ConnectX adapter, leaf/spine switches and storage server. Label the data direction for training reads and checkpoint writes.",
        "GOAL: speak accurately about NVIDIA networking without turning the interview into a product catalog."),
    Day(83,"Networking interview checkpoint","End-to-end fabric mastery",
        "This checkpoint combines TCP/IP, Ethernet, RDMA, RoCE, InfiniBand, NVMe-oF and topology into one troubleshooting model.",
        "WHITEBOARD\n\nGPU → HOST MEMORY → NIC/HCA → LEAF/SPINE FABRIC → STORAGE NIC → STORAGE SOFTWARE → NVMe/SSD\n\nExplain where latency, congestion and failures can occur.",
        "QUESTIONS\n\nRDMA vs TCP?\nRoCEv2 requirements?\nInfiniBand HCA?\nSubnet Manager?\nPFC/ECN?\nOversubscription?\nNVMe-oF transports?",
        "SCENARIO\n\n‘256 GPUs show low utilization during dataset reads.’ Build hypotheses: storage throughput, network congestion, metadata, client CPU, filesystem layout, hot targets or application input pipeline.",
        "LAB: produce a complete fault-isolation tree from GPU utilization to storage media.",
        "INTERVIEW GOAL\n\nDo not guess. State what you would measure at each layer and what result would support or reject your hypothesis.",
        "YOU SHOULD BE ABLE TO: explain an AI storage network as an end-to-end system." )
)
