package com.hpcai270

// Days 95–100: architecture, observability, troubleshooting and interview mastery.
val hpcDaysPart11 = listOf(
    Day(95,"Observability for storage","Metrics, logs, traces and evidence",
        "Production infrastructure needs observability. A storage engineer should be able to correlate application symptoms with storage, network and compute telemetry.",
        "FOUR QUESTIONS\n\nWhat happened? → logs/events\nHow much? → metrics\nWhere? → topology/dependency map\nWhen? → timestamps/correlation\n\nUse evidence before changing configuration.",
        "METRICS\n\nCapacity, IOPS, bandwidth, latency percentiles, CPU, memory, queue depth, network utilization/errors, filesystem health and device latency.",
        "AI CONNECTION\n\nCorrelate GPU utilization with storage throughput and network behavior. A drop in GPU utilization at the same time as storage p99 latency rises is stronger evidence than either metric alone.",
        "INTERVIEW: ‘What dashboards would you build for AI storage?’ Include capacity, client count, aggregate/per-client throughput, latency percentiles, metadata rate, hot targets, network errors/congestion and recovery activity.",
        "LAB: design a dashboard for a 256-GPU cluster and define what each panel tells you and what action it could trigger.",
        "GOAL: turn telemetry into an engineering decision."),
    Day(96,"Capacity and performance planning","Sizing from workload requirements",
        "Architecture starts with workload requirements. Capacity alone is insufficient; an AI storage platform must deliver the required bandwidth, concurrency and recovery characteristics.",
        "INPUTS\n\nGPU count × expected data rate\nDataset size + growth\nCheckpoint size × frequency\nConcurrent jobs\nMetadata rate\nRetention\nRPO/RTO\nNetwork capacity",
        "EXAMPLE REASONING\n\nIf 128 GPUs each consume an average of 2 GB/s, the theoretical aggregate demand is 256 GB/s. Real systems require headroom and the actual application demand must be measured rather than assumed.",
        "DESIGN\n\nChoose storage tier → size storage servers/targets → size network → validate client scaling → add protection/recovery overhead → test application workload.",
        "INTERVIEW: ‘How much storage does 1 PB of raw hardware provide?’ Answer by discussing RAID/replication/erasure coding, filesystem overhead, reserved space and operational headroom rather than quoting raw capacity as usable.",
        "LAB: create a capacity + bandwidth sizing sheet for 128 GPUs, 10 TB/day growth and 4 TB checkpoints.",
        "YOU SHOULD BE ABLE TO: translate application requirements into storage architecture inputs."),
    Day(97,"Production troubleshooting masterclass","A repeatable incident framework",
        "Senior engineers are valued for structured troubleshooting. Use a consistent framework so incidents are faster, safer and easier to explain.",
        "FRAMEWORK\n\n1 DEFINE symptom\n2 SCOPE blast radius\n3 BUILD timeline\n4 MAP dependency path\n5 FORM hypotheses\n6 MEASURE\n7 CHANGE one variable\n8 VALIDATE\n9 DOCUMENT/prevent",
        "SCENARIO\n\n‘Training throughput fell 40% after a maintenance window.’\n\nCompare before/after metrics. Identify changed network paths, storage services, client configuration, filesystem state and scheduler workload.",
        "BAD RESPONSE\n\nRestart all storage services. Reboot clients. Replace disks.\n\nThese actions destroy evidence and can increase impact.",
        "GOOD RESPONSE\n\nPreserve evidence, isolate the first changed dependency, test a safe hypothesis, make the smallest reversible change and verify the measured outcome.",
        "INTERVIEW: explain this framework aloud using an NFS incident, a Lustre incident and an RDMA incident.",
        "LAB: write three incident reports with symptom, scope, evidence, root cause, remediation, validation and preventive action.",
        "GOAL: demonstrate senior operational maturity."),
    Day(98,"Architecture interview","Design an AI storage platform",
        "This is a full system-design interview. The interviewer is testing requirements gathering, trade-offs, failure-domain thinking and performance reasoning.",
        "QUESTION\n\n‘Design storage for 512 GPUs training large language models.’\n\nDo not immediately answer ‘Lustre’. Ask requirements first.",
        "QUESTIONS TO ASK\n\nDataset size?\nRead bandwidth?\nCheckpoint size/frequency?\nConcurrent jobs?\nMetadata rate?\nRetention?\nRPO/RTO?\nNetwork fabric?\nLocal NVMe available?\nCloud/object tier?\nBudget/growth?",
        "REFERENCE DESIGN\n\nGPU NODES → RDMA/FAST FABRIC → PARALLEL FILESYSTEM/DATA PLATFORM → FLASH/CAPACITY\n                               ↘ OBJECT/ARCHIVE\n\nUse local NVMe for appropriate scratch/cache workloads.",
        "TRADE-OFFS\n\nLustre vs Storage Scale vs modern data platform; Ethernet/RoCE vs InfiniBand; flash vs capacity; replication vs erasure coding; shared filesystem vs object-centric pipeline.",
        "LAB: write a two-page design document with assumptions, architecture, sizing, failure domains, security, monitoring, operations and cost considerations.",
        "INTERVIEW GOAL: show that you can ask the right questions before proposing technology."),
    Day(99,"Senior storage interview drill","Rapid-fire technical questions",
        "Use this day as a final technical drill. Answer from memory before reading any reference material.",
        "STORAGE\n\nBlock vs file vs object?\nNFS read path?\nS3 model?\nNVMe queues?\nNVMe-oF transports?\nRAID vs replication vs EC?\nIOPS vs throughput vs latency?",
        "HPC\n\nWhy parallel filesystem?\nLustre MDS/MDT/OSS/OST?\nStriping?\nMetadata storm?\nStorage Scale/GPFS?\nCeph MON/OSD/CRUSH?",
        "NETWORK\n\nRDMA?\nQP/CQ?\nRoCEv2?\nPFC/ECN?\nInfiniBand HCA?\nLeaf-spine?\nOversubscription?\nNVMe-oF/RDMA?",
        "AI\n\nGPU starvation?\nCheckpoint storm?\nGDS?\nNVLink vs network?\nSlurm vs Kubernetes?\nLocal NVMe vs shared filesystem vs object storage?",
        "BEHAVIORAL/SCENARIO\n\nTell me about a difficult storage incident.\nHow did you find root cause?\nHow do you handle customer pressure?\nHow do you validate a performance claim?\nHow do you communicate risk before a change?",
        "LAB: answer 30 questions aloud. For every weak answer, return to the relevant day and rebuild the concept from the architecture diagram.",
        "GOAL: convert knowledge into interview communication."),
    Day(100,"Final capstone","Prove you can think like an HPC + AI storage engineer",
        "Day 100 is not a celebration page; it is a practical examination. You should be able to connect Linux, storage, networking, distributed filesystems, AI workloads and troubleshooting into one mental model.",
        "FINAL WHITEBOARD\n\nUSER → SLURM/K8S → GPU NODE → CPU/MEMORY → NIC/HCA → FABRIC → PARALLEL FILESYSTEM / DATA PLATFORM → NVMe/FLASH → OBJECT/ARCHIVE\n\nMetadata, data, control and monitoring paths should be identifiable.",
        "CAPSTONE TASK\n\nDesign a 256-GPU AI training platform. Specify workload assumptions, storage tiers, filesystem choice, network technology, bandwidth target, protection, checkpoint strategy, monitoring, failure domains and incident response.",
        "PERFORMANCE TASK\n\nCreate a benchmark plan using FIO and IOR concepts. Define block/transfer size, client count, concurrency, read/write pattern, dataset size and success criteria. Explain why the benchmark represents the workload.",
        "TROUBLESHOOTING TASK\n\nGiven low GPU utilization, determine whether the bottleneck is compute, CPU preprocessing, storage metadata, storage bandwidth, network congestion, filesystem layout or GPU communication. State the metric that would prove each hypothesis.",
        "INTERVIEW TASK\n\nExplain your architecture for 15 minutes without notes. Then answer: ‘Why should we hire a storage administrator for an AI infrastructure role?’\n\nStrong theme: you already understand enterprise storage operations; you have deliberately expanded into Linux, distributed storage, high-speed networking, performance engineering and AI data paths.",
        "100-DAY STANDARD\n\nYou are not claiming 100 days equals years of production HPC experience. You are demonstrating a coherent technical foundation, hands-on labs, measurable performance methodology, architecture skills and the ability to troubleshoot across the stack. That is the profile to take into HPC/AI storage interviews." )
)
