package com.hpcai270

// Days 62–72: distributed storage, Ceph and storage engineering judgment.
val hpcDaysPart8 = listOf(
    Day(62,"Parallel filesystem benchmarking","Proving scale instead of quoting peak numbers",
        "A parallel filesystem benchmark must test scaling. Single-client throughput is useful as a baseline but does not prove cluster-level behavior.",
        "TEST MATRIX\n\n1 client → 4 → 16 → 64 clients\nMeasure aggregate bandwidth, per-client bandwidth, latency where meaningful, metadata behavior and scaling efficiency.",
        "BOTTLENECKS\n\nNetwork links, storage servers, storage pools, CPU, memory, filesystem coordination, client processes and backend arrays can all limit scaling.",
        "INTERVIEW\n\nHow do you know a filesystem scales? Increase concurrency systematically, plot aggregate throughput, observe utilization, identify the first saturation point and compare against application demand.",
        "LAB: create a benchmark table for 1/4/16/64 clients and calculate scaling efficiency. Keep the workload parameters constant.",
        "GOAL: reason from measurements rather than vendor peak specifications."),
    Day(63,"Ceph architecture","MON, MGR, OSD, MDS, RGW and RBD",
        "Ceph is a distributed software-defined storage platform that can provide block, object and file services. It is important modern storage knowledge and is architecturally different from Lustre.",
        "CORE COMPONENTS\n\nMON → cluster maps/quorum\nMGR → management/telemetry\nOSD → data storage and recovery\nMDS → CephFS metadata\nRGW → S3-compatible object gateway\nRBD → block devices",
        "KEY DISTINCTION\n\nCeph is not simply a filesystem. It is a distributed storage system with object, block and file interfaces. This versatility also creates operational complexity.",
        "AI CONNECTION\n\nCeph can serve object, block or file workloads in AI infrastructure. Suitability depends on throughput, latency, scale, workload pattern and operational model.",
        "INTERVIEW: explain Ceph in two minutes: MON quorum, MGR, OSDs, CRUSH placement, recovery, and the RBD/CephFS/RGW interfaces.",
        "LAB: draw a 3-node Ceph cluster with MON/MGR/OSDs and trace an RBD write and an S3 object separately.",
        "YOU SHOULD BE ABLE TO: distinguish Ceph from a parallel filesystem and explain its major services."),
    Day(64,"Ceph CRUSH","Topology-aware data placement",
        "CRUSH is Ceph's algorithmic data-placement mechanism. It maps data to storage locations based on cluster topology and rules.",
        "MODEL\n\nOBJECT → PG → CRUSH RULE → BUCKET HIERARCHY → OSDs\n\nTopology can represent host, rack, row and other failure domains.",
        "WHY IT MATTERS\n\nPlacement should avoid putting all replicas in the same failure domain. Host-aware placement helps a host failure avoid destroying every copy.",
        "PERFORMANCE\n\nCRUSH placement affects data distribution and load balance. Poor topology or overloaded OSDs can create uneven performance.",
        "INTERVIEW: CRUSH provides deterministic distributed placement based on topology and policy, supporting scale and failure-domain awareness.",
        "LAB: draw three hosts with two OSDs each and show why replicas should be distributed across hosts.",
        "YOU SHOULD BE ABLE TO: explain CRUSH as placement logic, not a cache or filesystem."),
    Day(65,"Ceph pools and PGs","Replication and erasure coding",
        "Ceph pools provide logical storage policy. Placement Groups help map objects into groups that are then placed on OSDs. Protection may use replication or erasure coding.",
        "PATH\n\nOBJECT → POOL → PG → CRUSH → OSD SET",
        "TRADE-OFF\n\nMore replicas consume more capacity but provide redundancy. Erasure coding can improve usable capacity but may add computation and I/O overhead, especially for small writes.",
        "AI CONNECTION\n\nLarge sequential datasets can tolerate different protection characteristics than metadata-heavy or latency-sensitive workloads. Protection should match workload and failure objectives.",
        "INTERVIEW: compare replication and erasure coding using usable capacity, overhead, recovery behavior, failure tolerance and workload size.",
        "LAB: calculate rough usable capacity for an example replicated profile and an example erasure-coded profile.",
        "GOAL: connect protection choices to workload and failure domains."),
    Day(66,"Ceph recovery","Why failure can reduce performance",
        "Distributed storage systems recover data after failures. Recovery consumes network, CPU and disk resources and can compete with application I/O.",
        "FAILURE → DETECTION → RECOVERY/BACKFILL → HEALTHY PLACEMENT",
        "PERFORMANCE EFFECT\n\nA system may remain available while latency rises because recovery consumes resources. Availability is not the same as normal performance.",
        "TROUBLESHOOTING\n\nCheck recovery activity, OSD utilization, network saturation, client latency and cluster health. Avoid aggressive changes without understanding the failure state.",
        "INTERVIEW: why can a Ceph cluster be healthy but slow? Recovery, uneven OSD load, network contention, gateway services, client workload or hardware can all contribute.",
        "LAB: simulate conceptually one failed OSD and list the resources recovery consumes.",
        "YOU SHOULD BE ABLE TO: explain recovery as a workload competing with production I/O."),
    Day(67,"Ceph troubleshooting","Cluster state to root cause",
        "Ceph troubleshooting should move from cluster state to the affected interface and then to the resource causing the symptom.",
        "DECISION TREE\n\nCluster unhealthy? identify failed component.\nObject slow? inspect RGW/backend.\nRBD slow? inspect client/network/OSDs.\nCephFS slow? inspect MDS/data path.\n\nDo not treat every issue as an OSD issue.",
        "INTERVIEW QUESTIONS\n\nWhat is an OSD? MON? CRUSH? PG? Replication vs EC? Why can recovery hurt performance? How do block, file and object interfaces differ?",
        "STRONG ANSWER\n\nState architecture → identify interface → establish scope → inspect health → isolate component → measure → change one variable → validate.",
        "LAB: create an incident worksheet containing symptom, hypotheses, evidence, commands, expected findings and remediation.",
        "CAREER VALUE\n\nKnowing Ceph alongside Lustre and Storage Scale demonstrates distributed-storage breadth.",
        "GOAL: whiteboard Ceph and compare it intelligently with parallel filesystems."),
    Day(68,"Distributed storage consistency","What happens when many systems access the same data?",
        "Distributed systems must define how data is coordinated when multiple clients read and write concurrently. Storage engineers need a practical understanding of consistency, ordering, locking and caching.",
        "CONCEPTS\n\nCLIENT CACHE → NETWORK → STORAGE STATE\n\nThe more layers that cache or reorder operations, the more important the consistency model becomes.",
        "INTERVIEW\n\nExplain why two clients writing the same file can require coordination. Discuss locks, ordering and application semantics without claiming that every storage system uses identical mechanisms.",
        "AI CONNECTION\n\nDistributed training often has many workers reading common datasets but may write separate shards/checkpoints. Designing access patterns to reduce unnecessary coordination can improve scalability.",
        "TROUBLESHOOTING\n\nWhen data appears stale or behavior is inconsistent, identify client caching, filesystem semantics, application behavior and server state before blaming media.",
        "LAB: create two Linux processes that read/write a shared test file and document the observed semantics on your chosen filesystem.",
        "YOU SHOULD BE ABLE TO: explain why distributed access requires coordination."),
    Day(69,"Snapshots and clones","Fast copies versus backup",
        "Snapshots and clones can provide point-in-time or space-efficient views, but they are not automatically a complete backup strategy. Understand the distinction between local recovery and independent protection.",
        "MENTAL MODEL\n\nLIVE DATA → SNAPSHOT → LOCAL RECOVERY\n\nBACKUP → INDEPENDENT COPY / TARGET → DISASTER RECOVERY",
        "AI USE\n\nSnapshots can protect datasets or checkpoints from accidental changes. Large-scale training environments need retention and capacity planning because snapshots consume metadata and/or storage resources depending on implementation.",
        "INTERVIEW\n\n‘Is a snapshot a backup?’ Answer: not by itself. A snapshot can be a recovery mechanism, but it may share the same failure domain as production storage.",
        "TROUBLESHOOTING\n\nIf snapshot growth is unexpected, inspect changed blocks/files, retention policy and workload churn. Never delete snapshots blindly during an incident.",
        "LAB: draw production, snapshot, backup target and disaster site; mark shared versus independent failure domains.",
        "GOAL: reason about data protection instead of equating every copy with backup."),
    Day(70,"Erasure coding and rebuild math","Capacity efficiency with a recovery cost",
        "Erasure coding stores data fragments plus parity/coding fragments so missing fragments can be reconstructed. It is a major concept in modern distributed storage.",
        "GENERIC MODEL\n\nK DATA FRAGMENTS + M PARITY FRAGMENTS\n→ tolerate failures according to the coding scheme\n\nUsable fraction is approximately K/(K+M) before other overheads.",
        "TRADE-OFF\n\nMore parity improves fault tolerance but reduces usable capacity and can increase write/rebuild work. Small random writes may be more challenging than large sequential writes.",
        "AI CONNECTION\n\nLarge datasets and object stores may benefit from capacity-efficient protection. High-performance scratch storage may choose different protection because latency and write bandwidth are more important.",
        "INTERVIEW: ‘Why not use maximum erasure coding everywhere?’ Discuss performance, rebuild complexity, failure domains, workload pattern and operational risk.",
        "LAB: calculate usable fraction for K=8,M=2 and K=12,M=4, then explain which has better capacity efficiency and why neither number is universally optimal.",
        "YOU SHOULD BE ABLE TO: discuss protection as an engineering trade-off."),
    Day(71,"Storage failure analysis","First failure, secondary symptoms and blast radius",
        "In complex storage incidents, the first visible alarm is not necessarily the root cause. Engineers correlate timestamps and dependencies to find the earliest causal event.",
        "CHAIN\n\nROOT FAILURE → SECONDARY ERRORS → APPLICATION SYMPTOM\n\nExample: link failure → retransmissions → I/O latency → training slowdown.",
        "METHOD\n\nBuild timeline → identify affected scope → compare healthy/affected paths → find shared dependency → validate hypothesis with measurements.",
        "INTERVIEW\n\n‘How do you avoid replacing hardware unnecessarily?’ Answer: establish evidence, isolate the failing layer and prove that replacing/changing the component addresses the measured symptom.",
        "LAB: create a mock timeline containing storage alert, switch alert, client latency spike and application failure. Decide which event you investigate first and why.",
        "GOAL: develop senior-level incident reasoning."),
    Day(72,"Distributed storage interview checkpoint","Lustre + Storage Scale + Ceph",
        "You now need to switch between three architectural models without mixing their terminology.",
        "WHITEBOARD\n\nLUSTRE: CLIENT → LNET → MDS/MDT + OSS/OST\nSTORAGE SCALE: CLIENT → CLUSTER → FILESYSTEM/FILESET → STORAGE POOLS/NSDs\nCEPH: CLIENT → RBD/CephFS/RGW → DISTRIBUTED CLUSTER → OSDs/CRUSH",
        "QUESTIONS\n\nWhy parallel filesystem?\nMetadata vs data path?\nHow does striping work?\nWhat is CRUSH?\nReplication vs EC?\nWhy does recovery hurt performance?\nHow would you benchmark?",
        "ANSWER STRUCTURE\n\nArchitecture → workload → symptom → scope → measurement → bottleneck → remediation → validation.",
        "LAB: explain each architecture aloud for five minutes without notes. Then compare them on performance, interface, protection, operations and workload fit.",
        "GOAL: be interview-ready on distributed storage fundamentals before moving into AI-specific infrastructure." )
)
