package com.hpcai270

// Days 6–10 — expanded field notes
val hpcDaysPart2 = listOf(
    Day(
        6,
        "Parallel computing",
        "One problem, many workers",
        "Parallel computing means dividing a workload so multiple execution units can make progress at the same time. The goal is not simply to own more machines; the application must be able to use them efficiently.\n\nAnalogy: one person sorting 1,000 boxes takes a long time. Ten people can sort ten groups at once — if the work can be divided.",
        "TYPES OF PARALLELISM\n\nData parallelism → many workers process different pieces of data.\nTask parallelism → different workers perform different tasks.\nNode-level parallelism → many cores/threads inside one server.\nCluster-level parallelism → many servers cooperate.\n\nThe more coordination required, the more the network and synchronization matter.",
        "Draw one workload split across 8 workers. Mark where synchronization and storage can become bottlenecks.",
        pages = listOf(
            "PARALLEL COMPUTING — THE CORE IDEA\n\nSequential:\nONE WORKER → Work A → Work B → Work C → Result\n\nParallel:\nWorker 1 → Part A ┐\nWorker 2 → Part B ├→ Combine → Result\nWorker 3 → Part C ┤\nWorker 4 → Part D ┘\n\nThe workload must be divisible, and the cost of coordination must not erase the benefit of parallelism.",
            "TYPES OF PARALLELISM\n\nData parallelism → many workers process different pieces of data.\nTask parallelism → different workers perform different tasks.\nThread parallelism → many threads execute inside one node.\nCluster parallelism → many nodes cooperate.\n\nReal HPC systems commonly combine several levels at once.",
            "SPEEDUP IS NOT INFINITE\n\nIf 8 workers are available but one part of the job must remain serial, that serial section limits total speedup. Communication, synchronization, load imbalance and I/O can also reduce scaling efficiency.\n\nThink like a storage engineer: adding more storage targets only helps if the application can generate enough parallel I/O to use them.",
            "REAL HPC WORKLOADS\n\nWeather models → split the simulation domain.\nCFD → distribute mesh calculations.\nMolecular dynamics → distribute simulation work.\nAI training → distribute tensors, batches or model work across accelerators.\n\nNVIDIA GPU clusters push this idea to thousands of accelerators, making communication and data movement critical infrastructure concerns.",
            "STORAGE CONNECTION\n\nA parallel application can request data from hundreds or thousands of workers at once. If storage provides only a narrow data path, compute waits.\n\nThat is why HPC storage is not simply 'a bigger NAS'. It is an engineered data path involving clients, network, filesystem, servers, media and concurrency.",
            "TOOLS YOU WILL EVENTUALLY USE\n\nLinux: iostat, vmstat, sar, pidstat\nStorage benchmark: fio\nParallel filesystem benchmark: IOR\nScheduler: Slurm\nNetwork: ip, ss, ethtool\n\nThese tools let you separate CPU, memory, network and storage bottlenecks instead of guessing.",
            "INTERVIEW CHECK\n\nQ: Does doubling the number of servers always halve runtime?\nA: No. Parallel efficiency can fall because of serial work, communication, synchronization, contention, load imbalance or I/O.\n\nQ: Why does this matter to storage?\nA: Storage must sustain the concurrency generated by the parallel application."
        )
    ),
    Day(
        7,
        "MPI",
        "Communication across nodes",
        "MPI (Message Passing Interface) is a standard programming model/API used by processes that may run on different machines. Each process normally has its own address space and explicitly exchanges messages.",
        "MENTAL MODEL\n\nNode A: Process 0 ─────► Node B: Process 1\n              message\nNode B: Process 1 ─────► Node C: Process 2\n\nMPI applications use point-to-point operations and collectives such as broadcast, reduce and all-to-all.",
        "Explain why an MPI job can be affected by network latency even when CPU and storage are fast. Then draw a 4-rank MPI job.",
        pages = listOf(
            "MPI IN ONE SENTENCE\n\nMPI lets independent processes exchange data and coordinate, including when those processes run on different nodes.\n\nThink of each process as a worker with its own desk. MPI is the communication system that lets workers exchange instructions and results.",
            "RANKS AND PROCESSES\n\nAn MPI program normally starts multiple processes called ranks. Each rank has an identifier, such as rank 0, rank 1, rank 2 and so on.\n\nNode 1 → ranks 0–3\nNode 2 → ranks 4–7\n\nThe application can use these ranks to divide a problem across the cluster.",
            "POINT-TO-POINT VS COLLECTIVES\n\nPoint-to-point:\nRank 0 ─────► Rank 1\n\nCollective:\n       ┌→ Rank 1\nRank 0 ┼→ Rank 2\n       └→ Rank 3\n\nBroadcast, reduce, gather and all-to-all are common collective patterns. Collective traffic can become extremely important at scale.",
            "THE NETWORK MATTERS\n\nMPI stack:\nApplication → MPI library → transport → NIC/HCA → switch/fabric → NIC/HCA → MPI process\n\nBandwidth determines how much data can move. Latency affects how quickly communication can happen. Congestion and packet behavior can reduce effective performance.",
            "HPC IMPLEMENTATIONS\n\nCommon MPI implementations include Open MPI and MPICH. Job schedulers such as Slurm allocate nodes and launch distributed applications.\n\nFor a storage engineer, the important lesson is that an 'application problem' can actually be caused by network latency, congestion, CPU placement or storage stalls.",
            "AI CONNECTION\n\nDistributed AI frameworks perform large amounts of collective communication. NVIDIA NCCL is optimized for GPU collectives.\n\nThe principle is similar to MPI: many workers exchange information so that a distributed computation behaves as one coordinated workload.",
            "INTERVIEW CHECK\n\nQ: What is a rank?\nA: An MPI process identity within a communicator.\n\nQ: Why does InfiniBand matter to HPC?\nA: High-performance fabrics can provide low-latency, high-bandwidth communication and RDMA capabilities needed by tightly coupled workloads.\n\nQ: Can storage be fast while MPI is slow?\nA: Absolutely. Compute, network and storage are separate parts of the data path."
        )
    ),
    Day(
        8,
        "OpenMP",
        "Parallelism inside a node",
        "OpenMP is a shared-memory programming model. A process can create multiple threads that execute portions of a workload concurrently while sharing the node's memory address space.",
        "ONE NODE\n\nCore 1 ─┐\nCore 2 ─┤\nCore 3 ─┼── shared memory\nCore 4 ─┤\nCore 5 ─┘\n\nOpenMP commonly uses compiler directives such as #pragma omp parallel and #pragma omp for.",
        "Compare MPI and OpenMP in five sentences. Then draw a hybrid 2-node job with MPI between nodes and OpenMP inside each node.",
        pages = listOf(
            "OPENMP IN ONE SENTENCE\n\nOpenMP provides a practical way to parallelize work using multiple threads inside a shared-memory machine.\n\nAnalogy: MPI is like separate offices communicating by phone; OpenMP is like several people working around the same table and sharing the same whiteboard.",
            "THREADS VS PROCESSES\n\nProcess → has its own virtual address space.\nThread → executes within a process and normally shares its process memory.\n\nOpenMP commonly creates a team of threads and divides loop iterations or other work between them.",
            "ONE NODE ARCHITECTURE\n\nCPU socket → cores → threads\n             ↓\n          memory\n\nSeveral threads can execute simultaneously, but they compete for shared resources such as memory bandwidth and caches.",
            "MPI + OPENMP\n\nNode 1: MPI rank 0 → 8 OpenMP threads\nNode 2: MPI rank 1 → 8 OpenMP threads\nNode 3: MPI rank 2 → 8 OpenMP threads\n\nMPI handles communication between nodes. OpenMP handles parallelism within each node. This hybrid model is common in HPC applications.",
            "NUMA WARNING\n\nLarge servers may have multiple CPU sockets and NUMA domains. A thread accessing memory attached to another socket can experience different latency and bandwidth characteristics.\n\nStorage engineers should know NUMA because I/O performance is affected by CPU placement, interrupt placement and memory locality.",
            "WHY THIS MATTERS FOR STORAGE\n\nSuppose an application uses 64 threads and each thread issues I/O. The storage system may see a very different workload from a single-thread benchmark.\n\nAlways ask: how many clients, processes, threads, I/O queues and outstanding requests are involved?",
            "INTERVIEW CHECK\n\nQ: MPI or OpenMP for two different servers?\nA: MPI is designed for communication between processes and can span nodes.\n\nQ: OpenMP across two servers?\nA: Not by itself; OpenMP is primarily shared-memory parallelism within a node. Combine MPI + OpenMP for multi-node applications."
        )
    ),
    Day(
        9,
        "HPC storage",
        "Throughput + concurrency",
        "HPC storage is designed around a different question from a traditional file server. Instead of asking only 'How much capacity do we have?', ask: 'Can hundreds or thousands of clients read and write the required data concurrently without starving compute?'",
        "THREE PERFORMANCE NUMBERS\n\nThroughput → GB/s or TB/s\nIOPS → operations per second\nLatency → time for an I/O operation\n\nAlso track block size, read/write ratio, sequential/random behavior, queue depth and concurrency.",
        "Why can a storage system that looks fast for one client perform badly with 1,000 concurrent clients? List at least five possible reasons.",
        pages = listOf(
            "HPC STORAGE IS A DATA PATH\n\nApplication → client → network → filesystem → storage servers → media\n\nEvery layer can limit performance. A high-end SSD does not guarantee high application throughput if the network, filesystem or server architecture is the bottleneck.",
            "THROUGHPUT\n\nThroughput measures how much data moves per unit time.\n\nExample: 20 GB/s means approximately 20 gigabytes of data can be transferred each second under the measured workload.\n\nHPC workloads may need many GB/s or TB/s because large datasets are consumed by many workers simultaneously.",
            "IOPS + LATENCY\n\nIOPS = completed I/O operations per second.\nLatency = time associated with an I/O request.\n\nA small random-read workload may care strongly about IOPS and latency. A large sequential training dataset may care more about sustained throughput. There is no single 'storage speed' number.",
            "PARALLEL I/O\n\nClient 1 ─┐\nClient 2 ─┤\nClient 3 ─┼──► parallel filesystem ──► target 1\nClient N ─┘                              target 2\n                                         target 3\n                                         target N\n\nThe architecture spreads work so the system can scale beyond one disk or one server.",
            "PRODUCTS TO RECOGNIZE\n\nDDN EXAScaler → Lustre-based high-performance filesystem.\nIBM Storage Scale → massively parallel file/data platform.\nDell PowerScale → scale-out NAS used for enterprise and AI/HPC workloads.\nWEKA and VAST → modern high-performance data platforms.\n\nLearn the architecture first; vendor names come second.",
            "GPU STARVATION\n\nGPU: ████████████ compute\nStorage: ███ data delivery\n\nIf storage and the data path cannot deliver data fast enough, accelerators can spend time waiting. In an AI factory, improving storage throughput can therefore improve effective utilization of expensive GPUs.",
            "INTERVIEW CHECK\n\nQ: What metrics would you collect?\nA: Throughput, IOPS, latency, queue depth, concurrency, CPU utilization, network utilization and workload pattern.\n\nQ: Why benchmark at multiple client counts?\nA: Because a system's scaling behavior under concurrency is often more important than its single-client peak."
        )
    ),
    Day(
        10,
        "Parallel filesystems",
        "Lustre, Storage Scale and BeeGFS",
        "A parallel filesystem is built so many clients can access file data concurrently across multiple servers and storage targets. This is a core HPC storage concept.",
        "LUSTRE MENTAL MODEL\n\nClients → MDS/MDT → metadata\nClients → OSS/OST → file data\n\nMDS = Metadata Server\nMDT = Metadata Target\nOSS = Object Storage Server\nOST = Object Storage Target",
        "Draw a Lustre architecture with 4 clients, 2 metadata services and 4 data targets. Explain where file metadata and file data go.",
        pages = listOf(
            "WHY PARALLEL FILESYSTEMS?\n\nTraditional file server:\nMany clients → one main server → storage\n\nParallel filesystem:\nMany clients → multiple filesystem services → multiple storage targets\n\nThe objective is parallel access and scalable aggregate performance.",
            "LUSTRE MENTAL MODEL\n\nClients → MDS/MDT → metadata\nClients → OSS/OST → file data\n\nMDS = Metadata Server\nMDT = Metadata Target\nOSS = Object Storage Server\nOST = Object Storage Target\n\nMetadata and file data are separate concepts and can be served by different components.",
            "WHAT IS METADATA?\n\nMetadata answers questions such as:\n• What is this file called?\n• Who owns it?\n• What permissions apply?\n• What are its timestamps?\n• Where are its data extents/objects represented?\n\nThink of metadata as the filesystem's catalog. Large data transfers and directory operations are different workloads.",
            "STRIPING\n\nA large file can be distributed across multiple storage targets.\n\nFile → [target 1] [target 2] [target 3] [target 4]\n\nMultiple targets can participate in the data path, increasing aggregate throughput when the workload is suitable. Striping decisions also affect contention and small-I/O behavior.",
            "OTHER PARALLEL FILESYSTEMS\n\nIBM Storage Scale evolved from GPFS and is widely positioned for HPC/AI and analytics.\nBeeGFS is another parallel filesystem used in technical computing.\nLustre is widely used in HPC and AI environments.\n\nThe implementations differ, but the central idea is parallel access to shared data.",
            "REAL PRODUCT CONNECTION\n\nDDN EXAScaler is a commercial Lustre-based platform aimed at HPC and AI.\nIBM Storage Scale is IBM's parallel file/data platform.\nDell, WEKA, VAST and other vendors also provide high-performance data platforms.\n\nYou will learn these architectures deeply in later sections of the book.",
            "FIELD RULE + INTERVIEW CHECK\n\nNever memorize acronyms without understanding the data path.\n\nQ: What happens when an application opens a file?\nA: It needs filesystem metadata operations before the data path can be used.\n\nQ: Why separate metadata from data?\nA: Their workload characteristics differ, so the architecture can scale and tune them independently."
        )
    )
)
