package com.hpcai270

// Days 57–61: IBM Storage Scale / GPFS and distributed data-platform thinking.
val hpcDaysPart7 = listOf(
    Day(57,"IBM Storage Scale / GPFS","A second major parallel filesystem",
        "IBM Storage Scale is a scale-out file and data platform descended from GPFS. The key interview skill is recognizing the architectural principles shared by parallel filesystems while understanding different administration models.",
        "ARCHITECTURE\n\nCOMPUTE CLIENTS → NETWORK → STORAGE SCALE CLUSTER\nThe cluster provides a shared namespace while data and metadata are distributed across storage resources.",
        "COMPARE\n\nLustre and Storage Scale both support parallel I/O, but commands, concepts, deployment and tuning differ. Never apply a Lustre command or assumption blindly to GPFS/Storage Scale.",
        "AI CONNECTION\n\nStorage Scale fits enterprise AI/HPC designs where a shared namespace serves large training datasets and many compute clients while integrating with broader data-management workflows.",
        "INTERVIEW\n\nWhy choose a parallel filesystem over traditional NAS? Discuss scale-out architecture, parallel access, aggregate throughput, large namespaces and workload requirements.",
        "LAB: compare NFS NAS and a parallel filesystem using client count, metadata operations, aggregate bandwidth and failure-domain diagrams.",
        "YOU SHOULD BE ABLE TO: explain GPFS/Storage Scale accurately without claiming it is identical to Lustre."),
    Day(58,"Storage Scale architecture","Filesets, pools and distributed data",
        "Storage Scale uses a distributed architecture with filesets, storage pools and cluster nodes. Focus on the relationship between namespace, metadata, data placement and clients.",
        "LAYERS\n\nAPPLICATION → POSIX NAMESPACE → STORAGE SCALE CLUSTER → STORAGE POOLS / NSDs → DISKS / ARRAY / FLASH",
        "FILESETS\n\nFilesets provide administrative boundaries within a filesystem and can be useful for quotas, management and namespace organization. Production commands should follow the installed version's documentation.",
        "PERFORMANCE\n\nParallel access means many nodes can generate I/O simultaneously. Performance depends on network, cluster nodes, storage pools, file layout, workload and client behavior.",
        "TROUBLESHOOTING\n\nSeparate namespace/metadata symptoms from bulk-data symptoms. Check whether only one fileset, pool, node or network path is affected.",
        "INTERVIEW: isolate a slow workload by scoping clients, filesystem/fileset behavior, cluster/node health, network and storage pools before changing configuration.",
        "LAB: draw namespace → fileset → storage pool → NSD → disk relationships and identify where capacity and performance are measured."),
    Day(59,"Parallel filesystem comparison","Lustre vs Storage Scale",
        "Senior interviews test whether you can compare technologies without turning the discussion into brand marketing. Compare architecture, workload fit, operations, networking and performance methodology.",
        "COMMON GROUND\n\nBoth provide shared parallel file access, distribute I/O, support large HPC workloads and scale beyond a single storage head.",
        "DIFFERENTIATE\n\nLustre uses MDS/MDT, OSS/OST and LNet terminology. Storage Scale has its own cluster, fileset, NSD and policy concepts. Their tools and failure behavior are not interchangeable.",
        "WORKLOAD THINKING\n\nLarge sequential reads → bandwidth. Many small files → metadata. Checkpoints → sustained writes and burst management. Mixed enterprise workloads → policy and data management may matter.",
        "INTERVIEW: ‘Which is better, Lustre or GPFS?’ Correct response: it depends on workload, operational expertise, ecosystem, deployment constraints, scale, networking and data-management requirements.",
        "LAB: make a comparison table with five common principles and five technology-specific terms.",
        "GOAL: demonstrate engineering judgment rather than vendor loyalty."),
    Day(60,"Distributed data placement","Where does the data actually live?",
        "In distributed filesystems, a logical path does not mean data is stored on one device. Filesystem and storage-layer policies determine physical placement.",
        "MODEL\n\nLOGICAL FILE → LAYOUT / PLACEMENT POLICY → MULTIPLE STORAGE RESOURCES → PHYSICAL MEDIA",
        "WHY IT MATTERS\n\nA performance problem may be poor distribution rather than slow media. Fast media cannot overcome a congested network or overloaded server.",
        "AI EXAMPLE\n\nA checkpoint may be distributed across many storage resources so many writers can make progress instead of serializing through one device.",
        "TROUBLESHOOTING\n\nLook for hot resources, imbalance, uneven clients, network hotspots and workload skew. Average cluster performance can hide one overloaded component.",
        "INTERVIEW: explain that physical placement and access path influence performance while the logical namespace abstracts those details from applications.",
        "LAB: draw three physical placement models: single device, striped targets and policy-based distributed placement."),
    Day(61,"Policy-based storage","Tiering and lifecycle thinking",
        "Large AI/HPC environments may use multiple storage classes. Hot training data may require flash performance while older data can move to capacity tiers or object storage.",
        "LIFECYCLE\n\nRAW DATA → PREPARED DATA → TRAINING → CHECKPOINT → VALIDATION → ARCHIVE",
        "POLICY\n\nPolicies can consider age, file type, path, project or other attributes to determine placement or management. The goal is to match cost and performance to access patterns.",
        "AI CONNECTION\n\nDo not assume every byte belongs on the fastest flash tier. Training hot sets, checkpoints, source datasets and archives have different access frequencies.",
        "INTERVIEW: design 5 PB storage by first asking about hot/warm/cold data, access patterns, throughput, metadata, protection, retention, recovery objectives and cost.",
        "LAB: design a three-tier lifecycle using high-performance filesystem + capacity/object tier + archive.",
        "YOU SHOULD BE ABLE TO: connect storage design to workload lifecycle and cost." )
)
