package com.hpcai270

// Days 1–5
val hpcDaysPart1 = listOf(
Day(1,"What is HPC?","The big picture","HPC = High-Performance Computing. Instead of asking one computer to do a huge calculation, HPC connects many powerful machines so work can happen in parallel.\n\nThink: BIG problem → many computers → one result.","THE 5 BUILDING BLOCKS\n\nCompute → CPU / GPU\nMemory → working space\nNetwork → moves data\nStorage → keeps datasets & results\nScheduler → decides who runs when\n\nAI is a major HPC workload.","Explain HPC aloud in 30 seconds. Draw a 3-node cluster."),
Day(2,"Inside an HPC cluster","Nodes and roles","A node is a computer in the cluster. Different nodes can have different jobs.\n\nLOGIN NODE: users connect here.\nCONTROL NODE: manages the cluster.\nCOMPUTE NODE: performs jobs.\nSTORAGE: serves data.","USER\n  ↓\nLOGIN → SCHEDULER → COMPUTE 1\n                     COMPUTE 2\n                     COMPUTE 3\n                          ↓\n                       STORAGE\n\nThe network is the glue.","Sketch this architecture without looking."),
Day(3,"CPU vs GPU","Why AI loves GPUs","CPU: fewer powerful, flexible cores. Great for operating systems and varied workloads.\n\nGPU: many parallel execution units. Excellent when the same operation is applied to huge amounts of data.","AI TRAINING\n\nDataset → Storage → Network → GPU memory → GPU compute\n\nA powerful GPU can sit idle if storage or networking cannot deliver data quickly enough.","Define CPU, GPU, GPU memory and GPU starvation."),
Day(4,"HPC software stack","Layers matter","A cluster is more than hardware. The stack turns machines into a usable system.\n\nHardware → drivers → Linux → network/storage → scheduler → applications.","Application\n ↓\nMPI / libraries\n ↓\nFilesystem: Lustre / GPFS / CephFS\n ↓\nStorage servers\n ↓\nNVMe / disks\n\nA slowdown anywhere can become application slowdown.","Map enterprise-storage layers to this stack."),
Day(5,"What is a job?","The scheduler's world","An HPC job is a request to run work using cluster resources. It can specify CPUs, GPUs, memory and time.\n\nThe scheduler queues jobs and decides when and where they run.","SLURM\n\nsbatch → submit\nsqueue → view jobs\nsinfo → inspect partitions\nscancel → stop\nsrun → run work\n\nYou request resources rather than choosing a random server.","Write down resources an AI training job might request.")
)
