package com.hpcai270

// Expanded field notes — Days 1–5
val day1Expanded = Day(
    1, "What is HPC?", "The big picture",
    "HPC = High-Performance Computing. It means using powerful computers, often working together, to solve problems that are too large, slow, or expensive for one ordinary machine.\n\nThe key idea is SCALE: split useful work across resources, move data efficiently, and coordinate the workers.",
    "REAL-WORLD ANALOGY\n\nImagine a huge warehouse order. One worker could pick every item, but 100 workers can pick different aisles at the same time.\n\nWorkers = compute nodes\nAisles/roads = network\nWarehouse = storage\nSupervisor = scheduler\nInventory catalogue = metadata\n\nHPC is the computer version of coordinating many workers.",
    "The basic HPC system has several layers:\n\n1. COMPUTE — CPUs and GPUs execute work.\n2. MEMORY — keeps active data close to compute.\n3. NETWORK — connects nodes and carries data.\n4. STORAGE — holds datasets, checkpoints and results.\n5. SCHEDULER — allocates resources to jobs.\n6. SOFTWARE — turns hardware into usable applications.",
    "AI TRAINING PIPELINE\n\nDataset → storage → network → GPU memory → GPU compute → checkpoint → storage\n\nThis is why HPC storage matters. A very fast GPU does not automatically make the whole application fast. If data arrives too slowly, the GPU can wait — called GPU starvation.",
    "PRODUCTS YOU WILL MEET\n\nCompute: NVIDIA DGX / HGX, NVIDIA H200 and Blackwell systems, AMD Instinct\nHigh-speed networking: NVIDIA ConnectX, Quantum InfiniBand, Spectrum Ethernet\nParallel storage: DDN EXAScaler, IBM Storage Scale\nEnterprise scale-out storage also appears in AI/HPC environments: Dell PowerScale, WEKA, VAST Data, Pure Storage FlashBlade.\n\nThese are examples to recognize, not a claim that every cluster uses all of them.",
    "STORAGE-ADMIN CONNECTION\n\nYou already know the question: “Where does the server get its data?”\n\nIn traditional enterprise storage, you may think NFS, SMB, SAN, arrays and RAID. In HPC/AI the same fundamental question remains, but hundreds or thousands of compute processes may need data concurrently.\n\nThat pushes us toward parallel filesystems, NVMe, NVMe-oF, RDMA and high-speed fabrics.",
    "HANDS-ON\n\nDraw a 3-node HPC cluster. Label CPU/GPU, memory, network and storage. Then explain in 30 seconds why a storage or network bottleneck can reduce GPU utilization.\n\nINTERVIEW CHECK\n• What does HPC stand for?\n• Why use multiple computers?\n• What is GPU starvation?\n• Name five HPC building blocks.\n\nYOU SHOULD NOW BE ABLE TO: explain HPC to a beginner and connect it to your storage background.",
    pages = listOf(
        "HPC = High-Performance Computing. It means using powerful computers, often working together, to solve problems that are too large, slow, or expensive for one ordinary machine.\n\nThe key idea is SCALE: split useful work across resources, move data efficiently, and coordinate the workers.",
        "REAL-WORLD ANALOGY\n\nImagine a huge warehouse order. One worker could pick every item, but 100 workers can pick different aisles at the same time.\n\nWorkers = compute nodes\nAisles/roads = network\nWarehouse = storage\nSupervisor = scheduler\nInventory catalogue = metadata\n\nHPC is the computer version of coordinating many workers.",
        "THE BUILDING BLOCKS\n\n1. COMPUTE — CPUs and GPUs execute work.\n2. MEMORY — keeps active data close to compute.\n3. NETWORK — connects nodes and carries data.\n4. STORAGE — holds datasets, checkpoints and results.\n5. SCHEDULER — allocates resources to jobs.\n6. SOFTWARE — turns hardware into usable applications.",
        "AI TRAINING PIPELINE\n\nDataset → storage → network → GPU memory → GPU compute → checkpoint → storage\n\nA very fast GPU does not automatically make the whole application fast. If data arrives too slowly, the GPU can wait — called GPU starvation.",
        "PRODUCT MAP\n\nCompute: NVIDIA DGX/HGX, NVIDIA H200 and Blackwell systems, AMD Instinct\nNetworking: NVIDIA ConnectX, Quantum InfiniBand, Spectrum Ethernet\nParallel storage: DDN EXAScaler, IBM Storage Scale\nOther AI/HPC storage examples: Dell PowerScale, WEKA, VAST Data, Pure Storage FlashBlade.",
        "STORAGE-ADMIN CONNECTION\n\nThe fundamental question is still: “Where does the server get its data?”\n\nEnterprise storage commonly uses NFS, SMB, SAN and arrays. HPC/AI may have hundreds or thousands of processes accessing data concurrently, so parallel filesystems, NVMe, NVMe-oF and RDMA become important.",
        "HANDS-ON + INTERVIEW\n\nDraw a 3-node cluster. Label CPU/GPU, memory, network and storage. Explain why a storage or network bottleneck can reduce GPU utilization.\n\nAnswer: What is HPC? Why multiple computers? What is GPU starvation? Name five building blocks.\n\nYOU SHOULD NOW BE ABLE TO explain HPC to a beginner and connect it to storage."
    )
)
