package com.hpcai270

val hpcDaysPart3 = listOf(
Day(11,"NVMe","Fast local storage","NVMe is a storage protocol designed for non-volatile memory, especially flash. It uses PCIe and a highly parallel command model to achieve low latency and high I/O rates.","STORAGE EVOLUTION\n\nHDD → SATA SSD → SAS SSD → NVMe SSD\n\nAI systems can use local NVMe for scratch space, caching and fast data staging.","Explain why NVMe can have lower latency than traditional disk storage."),
Day(12,"NVMe-oF","NVMe over Fabrics","NVMe-oF extends NVMe access across a network fabric. A host can access remote NVMe storage instead of using a directly attached device.","HOST → fabric → NVMe target\n\nCommon transports: TCP, RDMA and Fibre Channel.\n\nThe fabric adds distance and complexity, so latency, bandwidth and congestion matter.","Name the three common NVMe-oF transport families."),
Day(13,"RDMA","Remote Direct Memory Access","RDMA allows one machine to access memory on another machine with very low overhead compared with traditional networking paths.","GPU / CPU\n   ↓\nNIC ───────→ NIC\n     RDMA\n   ↓\nRemote memory / storage\n\nInfiniBand and RoCE are major RDMA-capable fabrics.","Define RDMA without using the words fast or low latency."),
Day(14,"InfiniBand & RoCE","The high-speed fabric","InfiniBand is a high-performance networking technology widely used in HPC and AI clusters. RoCE carries RDMA over Ethernet.","GPU servers\n  ↓\nNIC → InfiniBand fabric → NIC → Storage\n\nor\nNIC → RoCE Ethernet → NIC → Storage\n\nUFM helps administrators operate large InfiniBand fabrics.","Connect IB, RoCE, RDMA, NIC and fabric logically."),
Day(15,"Your complete HPC-AI picture","Connect everything","AI training needs compute, but compute is only useful when data can reach it efficiently. Storage and networking therefore become part of AI performance engineering.","DATASET\n ↓\nFILE / OBJECT STORAGE\n ↓\nLUSTRE / STORAGE SCALE\n ↓\nNVMe + STORAGE SERVERS\n ↓\nRDMA / INFINIBAND / ROCE\n ↓\nGPU SERVERS\n ↓\nNCCL / TRAINING\n ↓\nCHECKPOINT → STORAGE\n\nNext: administer the pieces.","Final test: explain the entire diagram to another storage administrator in 3 minutes.")
)
