package com.hpcai270

// Days 84–94: AI storage pipeline, GPU data movement, containers and schedulers.
val hpcDaysPart10 = listOf(
    Day(84,"AI storage pipeline","Dataset to GPU and back",
        "AI infrastructure is an end-to-end pipeline. Storage is valuable only when it keeps compute supplied with data at the rate the workload requires.",
        "PIPELINE\n\nDATASET → OBJECT/FILE STORAGE → CACHE/STAGING → HOST MEMORY → GPU MEMORY → COMPUTE\n                                              ↑\n                                      CHECKPOINTS / OUTPUTS",
        "BOTTLENECK THINKING\n\nSlow training may come from data decoding, filesystem metadata, network congestion, storage latency, insufficient caching, CPU preprocessing or GPU communication—not necessarily the SSD.",
        "INTERVIEW: ‘How do you troubleshoot low GPU utilization?’ Start from the GPU metric and trace backward through GPU memory, host memory, CPU/data loader, network, filesystem and storage.",
        "LAB: draw the pipeline for a 64-GPU training job. Mark every queue/buffer where data can wait.",
        "REAL WORLD\n\nModern AI systems combine GPU servers, high-speed networking and storage platforms such as DDN, VAST, WEKA, Pure FlashBlade or parallel filesystems depending on architecture.",
        "YOU SHOULD BE ABLE TO: explain storage performance in terms of application and GPU impact."),
    Day(85,"AI datasets and file formats","Why data shape affects storage",
        "AI datasets can contain millions of small samples or fewer large shards. File count, object size, compression and access pattern can change storage behavior dramatically.",
        "PATTERNS\n\nMANY SMALL FILES → metadata pressure\nLARGE SHARDS → sequential/high-bandwidth access\nRANDOM SAMPLES → IOPS/latency\nCHECKPOINTS → large sustained writes",
        "DATA LOADER\n\nSTORAGE → decode → transform → batch → host memory → GPU\n\nStorage can be fast while CPU decoding becomes the bottleneck.",
        "INTERVIEW: ‘Why shard a dataset?’ Larger sequential objects can reduce metadata operations and improve parallel streaming, although the best format depends on framework and workload.",
        "TROUBLESHOOTING: compare storage throughput with CPU utilization, data-loader queue depth and GPU idle time. Do not optimize storage blindly.",
        "LAB: design two datasets with identical total size but different file counts. Predict which stresses metadata and which favors streaming.",
        "GOAL: connect storage access pattern to AI application behavior."),
    Day(86,"Checkpointing","The write storm at the end of an iteration",
        "Checkpointing saves model state so training can resume after interruption. Large distributed jobs can create synchronized bursts of storage traffic.",
        "EVENT\n\nTRAINING → SYNCHRONIZED CHECKPOINT → MANY WRITERS → STORAGE BURST → TRAINING RESUMES",
        "STORAGE REQUIREMENTS\n\nHigh aggregate write bandwidth, predictable latency, sufficient capacity, parallel access and a retention strategy.",
        "PERFORMANCE\n\nA checkpoint can expose bottlenecks that ordinary dataset reads do not. Measure write throughput, client concurrency, filesystem layout and network utilization.",
        "INTERVIEW: ‘How would you reduce checkpoint impact?’ Consider asynchronous/checkpoint strategies, staging, parallel writes, storage tiering and retention—while preserving correctness and recovery objectives.",
        "LAB: calculate time to write a 4 TB checkpoint at sustained 20 GB/s and 80 GB/s, then discuss why measured application time may differ.",
        "YOU SHOULD BE ABLE TO: explain checkpointing as a workload event, not just a file write."),
    Day(87,"GPU Direct Storage","Reducing unnecessary data movement",
        "NVIDIA GPUDirect Storage (GDS) is designed to provide a direct path between storage and GPU memory for supported systems, reducing unnecessary CPU-mediated data movement.",
        "CONCEPTUAL PATH\n\nTRADITIONAL\nSTORAGE → CPU MEMORY → GPU MEMORY\n\nGDS-STYLE PATH\nSTORAGE → PCIe/NVMe + DMA PATH → GPU MEMORY\n\nExact path depends on hardware, driver and supported storage/network stack.",
        "WHY IT MATTERS\n\nMoving large datasets through CPU memory can consume bandwidth and CPU resources. Direct data paths can reduce overhead and improve data movement efficiency when the workload supports them.",
        "INTERVIEW: ‘Does GDS make any storage fast?’ No. It improves a supported data path; storage, filesystem, network, PCIe topology and application behavior still matter.",
        "TROUBLESHOOTING: validate support and topology first, then compare baseline versus GDS-enabled application behavior. Measure GPU utilization, CPU use, throughput and latency.",
        "LAB: draw PCIe topology with GPU, NVMe device and NIC. Explain why PCIe locality and bandwidth can matter.",
        "GOAL: understand data movement rather than treating GDS as a magic performance switch."),
    Day(88,"NVLink and GPU communication","Storage is only one part of AI data movement",
        "GPU systems also need high-speed GPU-to-GPU communication. NVIDIA NVLink/NVSwitch technologies are important concepts because distributed AI performance depends on communication as well as storage.",
        "SYSTEM VIEW\n\nSTORAGE → HOST/NIC → GPU\nGPU ↔ GPU via high-speed interconnect\nGPU ↔ NETWORK for distributed training",
        "INTERVIEW DISTINCTION\n\nNVLink is not a storage protocol. It connects GPU memory domains at very high bandwidth in supported systems. Storage and networking feed data into the compute fabric.",
        "AI CONNECTION\n\nIf GPUs communicate efficiently but starve waiting for data, storage/network becomes limiting. If storage is fast but GPU collectives are slow, storage optimization will not fix the bottleneck.",
        "LAB: make a bottleneck tree with three branches: storage/data input, GPU communication, and compute.",
        "INTERVIEW: ‘How do you determine whether storage or GPU communication is the bottleneck?’ Compare application I/O metrics, GPU utilization, collective communication metrics and network/fabric telemetry.",
        "YOU SHOULD BE ABLE TO: place storage correctly inside the complete AI system."),
    Day(89,"Containers for AI/HPC","Packaging the software stack",
        "Containers package application dependencies so workloads can run consistently across systems. In GPU environments, the host driver and container runtime must be compatible with the application stack.",
        "STACK\n\nHOST KERNEL/DRIVER\n ↓\nCONTAINER RUNTIME\n ↓\nGPU/NETWORK INTEGRATION\n ↓\nAPPLICATION + LIBRARIES\n\nContainers do not eliminate hardware and driver dependencies.",
        "AI CONNECTION\n\nFrameworks such as PyTorch and TensorFlow depend on CUDA/ROCm libraries and GPU runtime behavior. Reproducible containers reduce software drift.",
        "INTERVIEW: ‘Why use containers in HPC?’ Reproducibility, dependency isolation, portability and easier deployment. Then mention performance/security/integration considerations.",
        "LAB: run a basic Linux container, inspect its filesystem isolation and identify which host resources it still depends on.",
        "YOU SHOULD BE ABLE TO: explain containers without confusing them with virtual machines."),
    Day(90,"Kubernetes for AI infrastructure","Pods, nodes and scheduling",
        "Kubernetes orchestrates containerized workloads. In AI infrastructure it can schedule GPU workloads, services and data-processing components, while HPC environments may also use traditional batch schedulers.",
        "MODEL\n\nKUBERNETES CONTROL PLANE\n ↓\nNODES\n ↓\nPODS\n ↓\nCONTAINERS\n ↓\nGPU / NETWORK / STORAGE",
        "STORAGE\n\nPersistent volumes and storage interfaces connect workloads to data. High-performance AI may require specialized storage classes or direct access patterns.",
        "INTERVIEW: ‘Kubernetes or Slurm?’ They solve different scheduling/orchestration problems. Slurm is dominant in many traditional HPC batch clusters; Kubernetes is common for cloud-native/containerized platforms. Hybrid architectures exist.",
        "LAB: draw a Kubernetes GPU workload path from pod to persistent storage and network.",
        "TROUBLESHOOTING: distinguish pod scheduling failure, GPU resource allocation, storage mount failure, application error and network connectivity.",
        "GOAL: understand where a storage engineer fits in containerized AI platforms."),
    Day(91,"Slurm and storage","The HPC scheduler's relationship with I/O",
        "Slurm allocates compute resources to jobs. Storage performance can be strongly affected by job scheduling because many jobs may start, read and checkpoint simultaneously.",
        "JOB JOURNEY\n\nUSER → sbatch/srun → SLURM CONTROLLER → QUEUE → COMPUTE NODES → APPLICATION → STORAGE",
        "I/O STORM\n\nIf hundreds of jobs start at once, each may initialize environments and read datasets. Coordinating job starts or staging data can reduce synchronized pressure.",
        "INTERVIEW: ‘Why should a storage engineer understand Slurm?’ Because scheduling controls concurrency and therefore storage workload shape.",
        "LAB: write a simple Slurm job conceptually containing resource request, application command and output/checkpoint paths. Then identify its storage traffic.",
        "TROUBLESHOOTING: correlate job start times with storage latency/throughput spikes. Look for a scheduler-driven workload event.",
        "YOU SHOULD BE ABLE TO: connect compute scheduling to storage behavior."),
    Day(92,"AI cluster storage tiers","Local NVMe, parallel filesystem and object storage",
        "AI clusters often use multiple storage tiers because no single system optimizes latency, bandwidth, capacity, durability and cost simultaneously.",
        "REFERENCE\n\nLOCAL NVMe → ultra-low latency scratch/cache\nPARALLEL FILESYSTEM → shared high-throughput training/checkpoint data\nOBJECT STORAGE → durable large-scale datasets/archive",
        "DATA MOVEMENT\n\nOBJECT → STAGING → PARALLEL FS → GPU JOB → CHECKPOINT → OBJECT/ARCHIVE",
        "INTERVIEW: ‘Why not train directly from object storage?’ Sometimes you can, but POSIX semantics, access pattern, latency, throughput and framework requirements may favor a filesystem/cache/staging tier.",
        "LAB: choose a tier for five workloads: temporary compiler files, active dataset, model checkpoint, long-term archive, low-latency scratch.",
        "GOAL: design storage by workload instead of by product name."),
    Day(93,"AI storage architecture","Building a production reference design",
        "A production AI storage architecture should connect application requirements to compute, networking, storage services, protection and operations.",
        "REFERENCE\n\nGPU CLUSTER\n ↓ high-speed fabric\nPARALLEL FILESYSTEM / DATA PLATFORM\n ├─ metadata\n ├─ high-bandwidth data path\n └─ flash/capacity tiers\n ↓\nOBJECT / ARCHIVE\n\nManagement and monitoring span all layers.",
        "REQUIREMENTS\n\nGPU count, dataset size, read/write bandwidth, checkpoint size, concurrency, metadata rate, RPO/RTO, retention, security, growth and budget.",
        "INTERVIEW: ‘Design storage for 512 GPUs.’ Start with workload requirements and calculate aggregate data demand. Then select filesystem/object/local NVMe tiers and size network/storage capacity around measured needs.",
        "LAB: create your own 512-GPU reference architecture and annotate every component with purpose and failure domain.",
        "TROUBLESHOOTING: map any performance alert to this architecture and identify which layer owns the metric.",
        "GOAL: move from administrator to architect thinking."),
    Day(94,"AI infrastructure interview checkpoint","Storage + network + GPU + scheduler",
        "This checkpoint tests whether you can reason across the entire stack rather than answering only storage-product questions.",
        "WHITEBOARD\n\nUSER → SLURM/K8S → GPU NODE → CPU/MEMORY → NIC/HCA → FABRIC → STORAGE DATA PATH → NVMe/FLASH → OBJECT/ARCHIVE",
        "QUESTIONS\n\nWhy GPU starvation?\nHow do you size storage?\nLustre vs Storage Scale?\nNVMe-oF vs NFS?\nRDMA vs TCP?\nWhy checkpoint storms?\nWhere does GDS fit?\nHow does Slurm affect I/O?",
        "STRONG ANSWER\n\nRequirements → architecture → workload pattern → bottleneck hypothesis → measurement → design change → validation.",
        "LAB: record yourself explaining the diagram for ten minutes. Identify every acronym you cannot explain and research it before proceeding.",
        "GOAL: communicate like an AI infrastructure engineer, not only a traditional storage administrator." )
)
