package com.hpcai270

// Days 6–10
val hpcDaysPart2 = listOf(
Day(6,"Parallel computing","One problem, many workers","Parallelism means splitting work so multiple workers can make progress at the same time. Example: one worker processes a huge dataset; many workers process smaller pieces concurrently.","BIG DATASET\n  ↙  ↓  ↘\nCPU1 CPU2 CPU3 ... CPU100\n  ↘  ↓  ↙\n   RESULT\n\nOpenMP commonly shares work inside one node. MPI coordinates processes across nodes.","Give one example where parallelism helps."),
Day(7,"MPI","Communication across nodes","MPI = Message Passing Interface. It lets separate processes communicate, often across different compute nodes. Each process has its own memory and can exchange messages.","NODE A                 NODE B\nProcess 0 ──message──► Process 1\nProcess 0 ◄──message── Process 1\n\nDistributed applications communicate frequently. This makes network latency and bandwidth important.","Explain why MPI makes network latency and bandwidth important."),
Day(8,"OpenMP","Parallelism inside a node","OpenMP is a programming model for shared-memory parallelism. A program can create multiple threads that work on different pieces of the same task.","ONE NODE\n\nCore 1 ─┐\nCore 2 ─┤\nCore 3 ─┼→ shared memory\nCore 4 ─┤\nCore 5 ─┘\n\nMPI → usually processes across nodes\nOpenMP → threads inside a node", "Compare MPI and OpenMP."),
Day(9,"HPC storage","Throughput + concurrency","HPC storage must feed many clients concurrently at very high throughput. Single-client performance is not the whole story.","PARALLEL I/O\n\nClient 1 ─┐\nClient 2 ─┤\nClient 3 ─┼→ parallel filesystem → many targets\nClient N ─┘\n\nLustre and Storage Scale are designed for this workload.","Why can good single-client speed perform poorly with 1,000 clients?"),
Day(10,"Parallel filesystems","Lustre, GPFS and BeeGFS","A parallel filesystem spreads data and/or metadata across multiple resources so many clients can access the filesystem concurrently. Lustre is especially important in HPC and AI storage.","LUSTRE\nClients → MDS/MDT for metadata\nClients → OSS/OST for file data\n\nMetadata tells the system what exists and where. Data servers hold file contents.","Learn MDS, MDT, OSS and OST. Draw the flow.")
)
