package com.hpcai270

// Days 101–117: production Linux, networking and automation mastery.
val hpcDaysPart12 = listOf(
    Day(101,"Linux boot and system lifecycle","From firmware to a usable HPC node",
        "A production engineer must understand the node from power-on to workload. Follow firmware/UEFI → bootloader → kernel → init/systemd → drivers → network/storage discovery → cluster services → scheduler readiness.",
        "BOOT FLOW\n\nUEFI/BIOS → GRUB → Linux kernel → initramfs → systemd → drivers → mounts → networking → authentication → monitoring → scheduler agent.\n\nA node can be powered on yet still be unavailable to Slurm because one layer failed.",
        "COMMANDS\n\n`journalctl -b`, `systemctl --failed`, `dmesg -T`, `lsblk`, `lspci`, `lsmod`, `ip link`, `mount`, `df -h`.\n\nUse timestamps to correlate boot failures with hardware or firmware changes.",
        "REAL WORLD\n\nAfter replacing an HBA/NIC, verify PCIe discovery, driver binding, interface naming, firmware compatibility and cluster service health before returning the node to production.",
        "LAB\n\nBuild a boot checklist for a GPU node. Intentionally stop a noncritical service and identify it using systemctl/journalctl. Record evidence before remediation.",
        "INTERVIEW\n\n‘A compute node is powered on but Slurm marks it DOWN. What do you check?’ Answer in dependency order: reachability → OS health → daemon → resources → drivers → scheduler logs → recent changes.",
        "STANDARD\n\nYou should be able to explain the complete Linux node lifecycle without treating Linux as a black box."),
    Day(102,"systemd and services","Production service management",
        "HPC platforms contain many long-running services: scheduler agents, monitoring, authentication, storage clients, network agents and vendor daemons. systemd defines their lifecycle and dependencies.",
        "KEY MODEL\n\nUnit → dependency → start → readiness → restart policy → logs.\n\nUnderstand active, failed, enabled, masked and dependency states. A service being enabled does not mean it is currently healthy.",
        "COMMANDS\n\n`systemctl status <unit>`\n`systemctl cat <unit>`\n`systemctl list-dependencies <unit>`\n`systemctl is-enabled <unit>`\n`journalctl -u <unit> --since today`.",
        "OPERATIONS\n\nAvoid blind restarts. First inspect status and logs, identify why the service failed, determine blast radius, then restart if the action is safe and documented.",
        "LAB\n\nCreate a test service that writes a heartbeat to a log. Configure restart behavior, inspect its journal, stop it, recover it and verify the recovery path.",
        "INTERVIEW\n\nExplain the difference between a service being installed, enabled, active and healthy. Then explain how you would prove a daemon is the root cause of a cluster incident.",
        "GOAL\n\nOperate Linux services using evidence and dependency reasoning rather than memorized commands."),
    Day(103,"Linux kernel and drivers","Why hardware support is a software problem",
        "High-performance systems depend on kernel modules and drivers for GPUs, NICs, NVMe devices, filesystems and RDMA. Version compatibility can determine whether expensive hardware performs correctly.",
        "PATH\n\nPCIe device → vendor driver → kernel subsystem → userspace library/tool → application.\n\nExamples include NVIDIA GPU driver/CUDA, mlx5/RDMA, NVMe and filesystem client modules.",
        "COMMANDS\n\n`lspci -nnk` shows devices and drivers. `lsmod` shows modules. `modinfo` shows module metadata. `dmesg` exposes probe/firmware errors. `uname -r` identifies the kernel.",
        "FAILURE PATTERN\n\nHardware appears in `lspci` but the expected driver is absent. Do not blame the hardware immediately. Check kernel compatibility, firmware, module loading, DKMS/package state and secure-boot restrictions.",
        "LAB\n\nOn a Linux VM, map every visible PCI device to its kernel driver. Create a troubleshooting sheet: device → driver → firmware → userspace validation command.",
        "INTERVIEW\n\n‘The NIC exists but RDMA tools show no device. Where do you start?’ Explain the chain from PCIe discovery through driver, firmware and RDMA subsystem to userspace.",
        "GOAL\n\nUnderstand hardware/software boundaries well enough to troubleshoot without immediately escalating."),
    Day(104,"Linux memory and NUMA","Why locality matters in HPC",
        "NUMA means memory access cost depends on which CPU socket owns the memory. GPU servers, high-speed NICs and NVMe devices also have PCIe locality. Poor placement can reduce performance even when utilization looks normal.",
        "MENTAL MODEL\n\nCPU socket ↔ local RAM ↔ PCIe root complex ↔ NIC/GPU/NVMe.\n\nA process using a remote NUMA node may pay additional latency and consume inter-socket bandwidth.",
        "TOOLS\n\n`lscpu`, `numactl --hardware`, `numactl -H`, `numastat`, `taskset`, `nvidia-smi topo -m`.\n\nInterpret topology before changing affinity.",
        "AI CONNECTION\n\nData preprocessing, storage networking and GPU feeding can become CPU/NUMA bottlenecks. A fast storage system cannot compensate for poorly placed CPU work indefinitely.",
        "LAB\n\nCompare a memory benchmark with default placement versus controlled NUMA placement. Record bandwidth, latency and CPU utilization. Explain the result.",
        "INTERVIEW\n\n‘Why can adding CPUs fail to improve an HPC workload?’ Discuss memory bandwidth, NUMA locality, synchronization and I/O rather than only core count.",
        "GOAL\n\nTreat topology as part of performance engineering."),
    Day(105,"Linux CPU scheduling and affinity","Controlling where work executes",
        "CPU affinity limits a process or thread to selected CPUs. In HPC, affinity can reduce contention and improve cache and NUMA locality, but over-constraining processes can also hurt performance.",
        "CONCEPTS\n\nCPU set, affinity, pinning, SMT/hyperthreading, NUMA locality, oversubscription.\n\nScheduler-level placement and application-level placement must agree.",
        "TOOLS\n\n`taskset -cp PID`, `ps -eo pid,psr,comm`, `lscpu -e`, `numactl`.\n\nFor clusters, Slurm CPU binding options must be understood rather than copied blindly.",
        "TROUBLESHOOTING\n\nIf one CPU is saturated while others are idle, inspect process placement, thread count and affinity. If every CPU is saturated but throughput is poor, investigate memory, I/O or synchronization.",
        "LAB\n\nRun a multithreaded workload with unrestricted and pinned CPU sets. Compare runtime, CPU utilization and memory locality.",
        "INTERVIEW\n\nExplain CPU affinity, NUMA affinity and GPU affinity as one topology problem. State when pinning helps and when it can make things worse.",
        "GOAL\n\nReason about CPU placement as part of the complete GPU/storage path."),
    Day(106,"Linux networking internals","From interface to socket",
        "Before learning RDMA deeply, master the ordinary Linux network path: application → socket → TCP/UDP → IP → routing → interface → NIC → switch.",
        "KEY OBJECTS\n\nsocket, port, route, neighbor/ARP, MTU, VLAN, bond, bridge, namespace, interface queue.\n\nHPC fabrics add specialized transports, but these fundamentals remain essential.",
        "COMMANDS\n\n`ip addr`, `ip route`, `ip neigh`, `ss -s`, `ss -lntp`, `ethtool`, `ping`, `tracepath`, `tcpdump`.\n\nUse packet captures only after defining the hypothesis.",
        "FAILURE MODEL\n\nNo connectivity can mean link down, VLAN error, route error, firewall, MTU mismatch, neighbor failure, service not listening or application-level rejection.",
        "LAB\n\nCreate two Linux VMs. Trace a TCP connection from listening socket to packet capture. Change an MTU or route in a controlled lab and identify the symptom.",
        "INTERVIEW\n\n‘Ping works but the application fails.’ Explain why ICMP success proves very little about TCP ports, MTU, routing, firewall rules or application state.",
        "GOAL\n\nBecome dangerous—in a good way—at isolating network failures layer by layer."),
    Day(107,"Routing, MTU and jumbo frames","The details that break high-speed networks",
        "High-performance networks depend on correct MTU and routing. Jumbo frames can reduce packet overhead but only work when the complete path supports the chosen size.",
        "PATH\n\nHost MTU → NIC → switch port → fabric → destination NIC → destination host.\n\nA single smaller link can create fragmentation, drops or mysterious application behavior.",
        "TOOLS\n\n`ip link`, `ip route`, `tracepath`, `ping -M do -s <size>`, `ethtool -S`, switch telemetry.\n\nTest the real path, not only the local interface configuration.",
        "AI CONNECTION\n\nLarge AI transfers make packet loss, congestion and MTU inconsistencies expensive. RDMA/RoCE environments require especially disciplined fabric configuration.",
        "LAB\n\nMeasure the largest non-fragmented packet between two lab hosts. Document interface MTU, path MTU and observed errors.",
        "INTERVIEW\n\nExplain why an MTU mismatch can cause performance degradation rather than a total outage. Discuss retransmission, fragmentation and transport behavior.",
        "GOAL\n\nMake MTU a measured property of a path, not a value copied from a configuration file."),
    Day(108,"Bonds, LACP and redundancy","Resilient Ethernet paths",
        "Enterprise and AI management networks frequently use link aggregation for capacity and resilience. Understand active-backup versus LACP and the difference between link redundancy and true path redundancy.",
        "DESIGN\n\nHost NICs → bond → switch pair/MLAG or equivalent.\n\nTwo links to one switch can still leave a switch failure domain. Separate paths are stronger than merely adding cables.",
        "TOOLS\n\n`cat /proc/net/bonding/bond0`, `ip -d link`, switch LACP state and interface counters.\n\nVerify hashing behavior and failure detection.",
        "OPERATIONS\n\nA healthy bond can hide a degraded member. Monitor member state, errors and throughput distribution rather than checking only ‘bond UP’.",
        "LAB\n\nConfigure a bond in a VM lab or document a production-equivalent design. Simulate a member failure and define expected application impact.",
        "INTERVIEW\n\nExplain why LACP does not necessarily double the throughput of one TCP flow. Discuss hashing, multiple flows and failure domains.",
        "GOAL\n\nSeparate redundancy, aggregate capacity and fault-domain design."),
    Day(109,"Bash engineering","Scripts that survive production",
        "A senior infrastructure engineer writes scripts that fail safely. Learn quoting, exit codes, traps, functions, arrays, validation and logging—not just one-line commands.",
        "PATTERN\n\n`set -euo pipefail` can improve safety when understood. Validate inputs. Quote variables. Check command results. Use functions. Emit timestamps. Never hard-code credentials.",
        "PRODUCTION STRUCTURE\n\nINPUT → VALIDATE → DISCOVER → CHANGE → VERIFY → REPORT.\n\nThe verification phase is what turns a script into an operational tool.",
        "STORAGE EXAMPLE\n\nA health script should discover targets, collect state, classify failures, produce a deterministic report and return a useful exit status. It should not silently continue after a failed SSH or API call.",
        "LAB\n\nWrite a Linux storage inventory script using `lsblk`, `findmnt`, `df`, `ip` and `systemctl`. Add logging and a summary section.",
        "INTERVIEW\n\nExplain how you prevent a Bash script from making a destructive change to every node because one input was wrong.",
        "GOAL\n\nMove from ‘I can script’ to ‘I can safely automate operations.’"),
    Day(110,"Python for infrastructure","Automation beyond shell scripting",
        "Python becomes valuable when automation needs structured data, APIs, concurrency, testing or reusable modules. Storage and HPC platforms expose both REST APIs and command-line interfaces.",
        "CORE SKILLS\n\nfunctions, modules, dictionaries/lists, exceptions, JSON, YAML, subprocess, pathlib, logging, argparse, virtual environments, requests/HTTP concepts.",
        "AUTOMATION PATTERN\n\nAPI/SSH input → parse structured state → normalize → classify → output JSON/CSV/HTML → alert.\n\nKeep collection separate from presentation.",
        "LAB\n\nBuild a Python inventory collector that reads a host list, runs a safe read-only command, parses output and emits JSON plus a summary table. Add retry and timeout handling.",
        "PRODUCTION\n\nUse timeouts, bounded retries, idempotency and structured logging. Never let one dead host stall the entire fleet indefinitely.",
        "INTERVIEW\n\nWhen would you choose Bash, Python or Ansible? Bash for simple local pipelines, Python for application logic/API workflows, Ansible for declarative multi-host configuration and orchestration.",
        "GOAL\n\nBe able to automate a storage fleet instead of administering nodes one by one."),
    Day(111,"Ansible for HPC infrastructure","Repeatable configuration at scale",
        "Ansible turns configuration into code. In HPC, it can standardize OS settings, users, packages, drivers, monitoring agents, mount configuration and cluster prerequisites.",
        "MODEL\n\nInventory → variables → playbook → modules → idempotent desired state → report.\n\nDo not mix secrets into plain-text playbooks.",
        "KEY CONCEPTS\n\nInventory groups, facts, handlers, templates, roles, tags, check mode, diff mode, vault, serial execution and failure handling.",
        "HPC USE\n\nGroup nodes by role: login, management, compute, storage client, GPU. Apply common baseline first, then role-specific configuration.",
        "LAB\n\nCreate an Ansible role that installs a monitoring package, writes a configuration template and restarts only when configuration changes. Run twice and prove idempotency.",
        "INTERVIEW\n\nExplain why idempotency matters. A good answer includes safe reruns, predictable state and reduced configuration drift.",
        "GOAL\n\nThink of infrastructure as a reproducible system rather than a collection of manually tuned servers.")
)
