package com.hpcai270

// Days 46–56: Lustre from fundamentals to production troubleshooting.
val hpcDaysPart6 = listOf(
    Day(46,"Lustre architecture","MDS, MDT, OSS, OST and clients",
        "Lustre is a parallel distributed filesystem designed for very high aggregate I/O. Unlike a traditional NAS, data and metadata services are distributed so many clients can operate concurrently.",
        "ARCHITECTURE\n\nCLIENTS → LNet/FABRIC → MDS/MDT for metadata\n                     ↘ OSS/OST for file data\n\nMDS answers questions such as ‘where is this file and who owns it?’ OSS servers move file data to and from OST targets.",
        "TERMS\n\nMDS = Metadata Server\nMDT = Metadata Target\nOSS = Object Storage Server\nOST = Object Storage Target\nLNet = Lustre networking layer\nClient = compute node mounting Lustre\n\nDo not confuse an OST with an individual disk; an OST is a Lustre storage target backed by storage devices.",
        "WHY IT MATTERS\n\nAI training may have hundreds or thousands of clients. A centralized NAS head can become a bottleneck. Lustre distributes the data path so aggregate bandwidth can scale across multiple targets.",
        "TROUBLESHOOTING MODEL\n\nMount problem → client/LNet/DNS/configuration\nMetadata problem → MDS/MDT\nData I/O problem → OSS/OST/network\nOne file slow → striping/layout/workload\nWhole filesystem slow → shared fabric or service saturation\n\nAlways identify the affected layer before changing anything.",
        "LAB + INTERVIEW\n\nLab: draw a Lustre cluster with 4 clients, 2 MDS/MDT services and 4 OSS/OST targets. Trace a file create and a 1 GB read separately.\n\nInterview: ‘Why does Lustre separate metadata and data services?’\n\nYOU SHOULD BE ABLE TO: explain the complete Lustre data and metadata paths without using vendor buzzwords."),

    Day(47,"Lustre metadata","The namespace control plane",
        "Metadata operations include creating files, looking up names, changing permissions and managing directories. These operations are fundamentally different from moving the file's bulk data.",
        "METADATA PATH\n\nopen('/data/a')\n → client VFS\n → Lustre metadata client\n → MDS/MDT\n → inode/directory information\n → client receives layout/location\n\nDATA PATH\n\nread() → OSTs → data → client\n\nThe two paths cooperate but have different bottlenecks.",
        "SMALL FILE PROBLEM\n\nMillions of tiny files can create enormous metadata pressure even when total capacity is small. Directory traversal, stat(), create(), unlink() and permission checks can dominate the workload.",
        "AI CONNECTION\n\nA dataset containing millions of small samples can produce metadata storms when many workers start together. Packing data into larger shards can reduce metadata pressure and improve sequentiality.",
        "TROUBLESHOOTING\n\nHigh metadata latency with low data bandwidth suggests an MDS/MDT or namespace workload issue. High data latency with normal metadata suggests OSS/OST, network or backend I/O.",
        "LAB + INTERVIEW\n\nLab: create 100,000 small files in a safe local filesystem and observe why file creation is different from reading one large file.\n\nInterview: ‘Why can a 1 TB filesystem struggle with a 1 million-file workload?’\n\nYOU SHOULD BE ABLE TO: distinguish metadata I/O from bulk data I/O."),

    Day(48,"Lustre striping","How one file uses many targets",
        "Lustre can stripe a file across multiple OSTs. Striping allows different clients and servers to participate in the I/O of a single large file, increasing parallelism when the workload benefits from it.",
        "CONCEPT\n\nFILE\n ├─ stripe 0 → OST1\n ├─ stripe 1 → OST2\n ├─ stripe 2 → OST3\n └─ stripe 3 → OST4\n\nThe client uses the file layout to direct I/O to the correct targets.",
        "STRIPE PARAMETERS\n\nStripe count = number of OSTs used.\nStripe size = amount written before moving to the next stripe.\nLayout choice should match workload rather than maximizing every value.",
        "AI EXAMPLE\n\nA large checkpoint file written by many processes can benefit from broad striping. A tiny configuration file does not need to consume dozens of OSTs.",
        "FAILURE/PERFORMANCE\n\nToo little striping can underuse storage. Excessive striping can increase coordination and metadata/layout overhead. One overloaded OST can become the limiting factor for a poorly distributed layout.",
        "LAB + INTERVIEW\n\nLab: inspect Lustre file layout with Lustre tools in a lab environment. Compare a single-target file with a broadly striped file.\n\nInterview: ‘What is stripe count and when would you increase it?’\n\nYOU SHOULD BE ABLE TO: explain striping as controlled parallelism, not simply ‘RAID across servers’."),

    Day(49,"Lustre LNet","The network layer of Lustre",
        "LNet is Lustre's networking abstraction. It lets Lustre communicate across supported network transports and provides the path between clients and Lustre servers.",
        "PATH\n\nCLIENT\n ↓\nLUSTRE CLIENT\n ↓\nLNET\n ↓\nETHERNET / TCP or RDMA FABRIC\n ↓\nOSS / MDS\n\nThe exact transport depends on the environment.",
        "WHY STORAGE ENGINEERS CARE\n\nA storage server can have excellent disks while the filesystem remains slow because of network loss, congestion, link speed, MTU mismatch, routing, RDMA problems or fabric contention.",
        "TROUBLESHOOTING\n\nFirst test physical/link health. Then IP connectivity where applicable. Then transport/fabric health. Then LNet state and Lustre service health. Finally measure filesystem I/O.",
        "PERFORMANCE\n\nFor high-throughput systems, multiple network interfaces and routes may be used. The goal is to avoid a single network path limiting many OSTs or clients.",
        "LAB + INTERVIEW\n\nLab: map client NIC → switch → server NIC before touching filesystem settings.\n\nInterview: ‘If fio against a local disk is fast but Lustre is slow, what layers do you investigate?’\n\nAnswer path: client → LNet → fabric → server → filesystem → backend device.",
        "YOU SHOULD BE ABLE TO: treat the network as part of the storage system, not an external dependency."),

    Day(50,"Lustre administration","Mounts, health and service thinking",
        "Production Lustre administration combines Linux administration, filesystem configuration, target health, networking and controlled change management.",
        "ADMIN CHECKLIST\n\n1. Client mount state\n2. MDS/MDT health\n3. OSS/OST health\n4. Network/LNet health\n5. Capacity and inode usage\n6. Error logs\n7. I/O performance\n8. Recent changes\n\nNever start by restarting everything.",
        "OPERATIONAL PRINCIPLE\n\nA filesystem can be ‘up’ while one target is degraded, one network path is failing or metadata latency is high. Availability is not the same as performance health.",
        "CAPACITY\n\nMonitor both bytes and inode/file counts. A filesystem can have free terabytes but still run out of inodes or suffer metadata pressure.",
        "CHANGE SAFETY\n\nRecord configuration before changes. Make one controlled change. Observe. Roll back if necessary. Avoid destructive formatting or repair operations unless the procedure is fully understood.",
        "LAB + INTERVIEW\n\nLab: build a checklist for a hypothetical Lustre morning health check.\n\nInterview: ‘What would you check before declaring a Lustre incident resolved?’\n\nInclude service health, target health, client impact, errors, network, performance and evidence after remediation."),

    Day(51,"Lustre performance","Benchmarking a parallel filesystem",
        "Lustre performance must be measured with workloads that reflect the application. A single fio test from one client does not characterize a large parallel filesystem.",
        "TEST LEVELS\n\nSingle client → basic latency/bandwidth\nMultiple clients → scaling\nMany clients → aggregate throughput\nMetadata test → create/stat/delete behavior\nLarge sequential I/O → bandwidth\nSmall random I/O → IOPS/latency",
        "IOR\n\nIOR is commonly used for parallel filesystem benchmarking. It can exercise multiple processes and clients and report aggregate bandwidth. FIO remains valuable for controlled block/file workloads.",
        "METHODOLOGY\n\nRecord client count, process count, block/transfer size, read/write pattern, stripe layout, dataset size, cache state and network configuration. Repeat tests and compare like with like.",
        "COMMON ERROR\n\n‘The array can do 100 GB/s, so Lustre should do 100 GB/s.’\n\nNot necessarily. Network, OSS count, stripe distribution, clients, filesystem settings and application pattern all constrain end-to-end throughput.",
        "INTERVIEW\n\n‘How would you benchmark a new Lustre system?’\n\nAnswer: establish baseline → test one client → scale clients → test metadata → test application-like workload → identify saturation → document bottleneck and repeat after change.",
        "YOU SHOULD BE ABLE TO: design a defensible performance experiment instead of quoting vendor peak numbers."),

    Day(52,"Lustre failure domains","Understanding what can fail",
        "A production parallel filesystem contains many independent components. Good engineers reason about failure domains rather than treating the filesystem as one box.",
        "FAILURE DOMAINS\n\nClient node\nNIC/link\nSwitch/fabric\nMDS/MDT\nOSS/OST\nBackend disks\nPower/control plane\nConfiguration\n\nThe blast radius depends on which component fails.",
        "EXAMPLE\n\nOne OST unavailable → files whose data resides there may be affected while unrelated data remains accessible. One client failing should not normally take the filesystem down for everyone.",
        "HA THINKING\n\nRedundancy can exist at metadata, server, network and storage layers. But redundancy is only useful if failover is correctly configured and tested.",
        "TROUBLESHOOTING\n\nCorrelate timestamps across client logs, filesystem logs, network telemetry and storage alerts. Look for the first failure, not the loudest later error.",
        "INTERVIEW\n\n‘How do you determine blast radius during a Lustre outage?’\n\nMap affected clients, paths, targets and operations; identify common infrastructure; compare healthy versus affected workloads; then isolate the shared dependency.",
        "LAB: draw three incidents—single client failure, single OST failure, fabric failure—and predict symptoms for each."),

    Day(53,"Lustre quotas and capacity","Capacity is more than free space",
        "Capacity planning in HPC includes usable bytes, inode availability, metadata capacity, target balance, expected growth and workload behavior.",
        "THINK IN DIMENSIONS\n\nTB/PB capacity\nIOPS\nGB/s bandwidth\nMetadata operations/sec\nInodes\nNetwork bandwidth\nServer CPU/RAM\n\nA system can be healthy in one dimension and exhausted in another.",
        "QUOTAS\n\nQuotas can constrain users, groups or projects. Understand whether an application is failing because the physical filesystem is full or because an administrative quota was reached.",
        "AI CONNECTION\n\nTraining datasets grow rapidly, but checkpoint retention can create bursty capacity requirements. Capacity planning should include peak checkpoint generation and retention policy, not only dataset size.",
        "TROUBLESHOOTING\n\n‘No space left’ does not always mean zero bytes. Check inode exhaustion, quotas, reserved space and the specific target or namespace condition.",
        "INTERVIEW\n\n‘What would you monitor for HPC storage capacity?’\n\nBytes, inode usage, growth rate, quota usage, target imbalance, metadata pressure, snapshot/retention impact and projected time-to-full.",
        "YOU SHOULD BE ABLE TO: perform a capacity conversation using measurable dimensions."),

    Day(54,"Lustre security","Identity, permissions and safe operations",
        "Lustre inherits important Linux permission concepts while adding distributed filesystem administration. Security must preserve access control without making troubleshooting impossible.",
        "IDENTITY\n\nUSER/GROUP → client credentials → filesystem permissions/policy → file access\n\nUnderstand UID/GID mapping and the environment's authentication design.",
        "LEAST PRIVILEGE\n\nDo not give applications or administrators more access than required. Separate operational privileges from user data access where possible.",
        "SECURITY + PERFORMANCE\n\nAuthentication and authorization add control-plane work, but security should not be ‘disabled for performance’ without a documented architecture and risk decision.",
        "TROUBLESHOOTING\n\nPermission denied → verify identity, ownership, mode bits, ACLs/policy and mount context. Do not assume storage hardware is the cause.",
        "INTERVIEW\n\n‘A user can mount the filesystem but cannot read a directory. What do you check?’\n\nCheck identity → mount/access context → directory ownership/mode → ACLs/policy → server-side logs.",
        "LAB: create users/groups in a Linux VM, test permissions and ACLs, and document the exact reason access succeeds or fails."),

    Day(55,"Lustre incident walkthrough","From symptom to root cause",
        "Interviewers often care more about your troubleshooting method than whether you remember a command. This day practices an end-to-end storage incident.",
        "SCENARIO\n\n‘AI training slowed dramatically. Storage dashboard shows normal capacity.’\n\nDo not jump to disk replacement. Establish scope, time, affected jobs and the exact performance symptom first.",
        "INVESTIGATION\n\n1. Is every job affected?\n2. One client or many?\n3. Metadata or data I/O?\n4. Read or write?\n5. Latency or bandwidth?\n6. Network errors/congestion?\n7. One OST/OSS hot?\n8. What changed immediately before incident?",
        "EVIDENCE\n\nUse application metrics, filesystem metrics, Linux telemetry, network counters and storage telemetry. Correlate timestamps. Preserve evidence before making broad changes.",
        "ROOT-CAUSE EXAMPLES\n\nA single overloaded OST from poor striping; a switch link issue; metadata storm from a new workload; backend rebuild contention; or client-side CPU/network saturation.",
        "INTERVIEW ANSWER\n\n‘I would first establish blast radius and workload shape, then trace the data path layer by layer. I would form hypotheses, gather evidence, change one variable at a time, validate recovery, and document prevention.’",
        "CAPSTONE: write a one-page incident report with symptom, impact, timeline, evidence, root cause, remediation, validation and preventive action."),

    Day(56,"Lustre interview mastery","Architecture, performance and troubleshooting",
        "This is the first structured interview checkpoint. You should be able to explain Lustre to a storage engineer, Linux administrator and AI infrastructure architect at different depths.",
        "MUST KNOW\n\nMDS/MDT vs OSS/OST\nMetadata vs data path\nLNet\nStriping\nClient architecture\nParallel I/O\nFailure domains\nCapacity vs performance\nFIO vs IOR\n\nDo not memorize definitions without tracing an actual read/write.",
        "WHITEBOARD\n\nDraw: GPU/compute node → fabric → Lustre client → MDS for metadata → OSS/OST for data → backend storage. Explain what happens when the file is opened, read and checkpointed.",
        "INTERVIEW QUESTIONS\n\nWhy parallel filesystem?\nWhy metadata separation?\nWhat causes metadata storms?\nHow does striping affect throughput?\nWhy can one OST bottleneck a workload?\nHow do you benchmark?\nHow do you isolate network vs storage?",
        "STRONG ANSWER PATTERN\n\nStart with architecture → define symptom → scope impact → identify layer → measure → test hypothesis → remediate → validate → prevent recurrence.",
        "HANDS-ON\n\nRebuild your Lustre diagram from memory and explain every arrow aloud. Then create a troubleshooting decision tree for mount failure, slow metadata and slow bulk I/O.",
        "GOAL\n\nYou are not expected to have years of production Lustre experience after a study program. You are expected to demonstrate accurate architecture, disciplined troubleshooting and hands-on learning evidence." )
)
