package com.hpcai270

/**
 * Practical deep-dive notes for the 45 currently published days.
 * Kept as valid Kotlin raw strings so the lesson content can contain
 * punctuation, commands and multiple paragraphs without escaping issues.
 */
fun depthNote(day: Int): String = when (day) {
    1 -> note("HPC IS A SYSTEM, NOT A SERVER", "Understand compute, memory, interconnect, storage, scheduling and software as one system. A high-FLOPS GPU cluster can still perform badly when the data or synchronization path is weak.", "Trace the path: application → CPU/GPU → memory → NIC/fabric → filesystem/storage → back again.", "INTERVIEW: If GPU utilization is low, investigate data loading, CPU preprocessing, memory pressure, network communication, filesystem latency and checkpointing before blaming the GPU.")
    2 -> note("CLUSTER ROLES", "Separate login, management/control, compute, storage and service nodes conceptually. Login nodes are normally for preparation and submission; compute nodes run production work.", "Learn BMC/IPMI/Redfish, provisioning, DNS, NTP, identity, monitoring and the Slurm job journey from login to allocated compute node.", "INTERVIEW: Explain how a job gets from SSH login to a GPU node and shared storage.")
    3 -> note("CPU, GPU AND MEMORY", "CPUs provide flexible control and strong individual cores; GPUs provide massive parallel arithmetic. AI performance also depends on HBM, host RAM, PCIe, NVLink and NVSwitch.", "Trace storage → NIC → host memory → GPU memory → compute. Every hop has bandwidth and latency limits.", "FIELD RULE: never say a GPU is simply faster; relate performance to workload, precision, memory bandwidth and parallelism.")
    4 -> note("THE HPC SOFTWARE STACK", "Know firmware, kernel, drivers, CUDA/ROCm, MPI, NCCL, OpenMP, libraries, modules, containers, schedulers, filesystems and monitoring.", "Version compatibility matters. Environment modules allow several compiler, MPI and CUDA stacks to coexist.", "TROUBLESHOOTING: identify the first failing layer instead of assuming every timeout is a storage-array problem.")
    5 -> note("JOBS AND SCHEDULING", "Learn job state, partition, priority, fair-share, reservations, backfill, wall time and resource constraints. Recognize sbatch, srun, squeue, sinfo, scancel, sacct and scontrol.", "A pending job may simply be waiting for GPUs, memory, constraints or priority. A running job may still be I/O- or communication-bound.", "STORAGE CONNECTION: checkpoint storms can create simultaneous write bursts from many jobs, so concurrency matters in capacity planning.")
    6 -> note("PARALLELISM AND SCALING", "Understand strong scaling and weak scaling. Speedup is limited by serial work, synchronization, communication, load imbalance and I/O.", "Amdahl's law provides the key intuition: a small serial fraction becomes important as worker count increases.", "EXERCISE: imagine 64 GPU nodes sharing one storage path and list every possible serialization point.")
    7 -> note("MPI", "Know rank, communicator, point-to-point operations and collectives such as broadcast, reduce, all-reduce, gather and all-to-all.", "MPI performance depends on process placement, CPU affinity, NIC selection, topology, latency, bandwidth and congestion.", "STORAGE CONNECTION: one slow node or I/O pause can delay tightly synchronized applications and make a storage problem appear as an application-wide slowdown.")
    8 -> note("OPENMP AND NUMA", "OpenMP creates threads within shared-memory processes. NUMA means memory access can have different cost depending on CPU socket and memory locality.", "I/O interrupts, network queues, CPU affinity and buffers interact with NUMA placement. Benchmark results can change with process and memory placement.", "FIELD RULE: record sockets, NUMA nodes, thread count, process count and I/O concurrency when investigating performance.")
    9 -> note("HPC STORAGE PERFORMANCE", "Define workload before measuring it: block size, access pattern, read/write ratio, concurrency, queue depth, client count, dataset size and cache state.", "Separate single-client results from aggregate cluster results. Training reads, checkpoint writes, metadata-heavy workloads and inference have different requirements.", "INTERVIEW: explain why a claim such as 20 GB/s is incomplete without workload conditions.")
    10 -> note("PARALLEL FILESYSTEMS", "Understand metadata versus data paths. Lustre uses metadata services/targets and object storage servers/targets; IBM Storage Scale evolved from GPFS; BeeGFS is another important HPC filesystem.", "Learn namespace, inode, metadata operation, data target, stripe, client, mount and recovery.", "REAL WORLD: DDN EXAScaler is a commercial Lustre platform used for HPC and AI. Learn the architecture first, then map vendor components onto it.")
    11 -> note("NVMe", "Know controller, namespace, submission queue, completion queue, queue pairs, PCIe lanes and the distinction between local NVMe and NVMe over Fabrics.", "Useful Linux tools include nvme list, nvme id-ctrl, nvme smart-log, lsblk, lspci and iostat.", "PERFORMANCE: queue count, queue depth, CPU placement, PCIe topology, firmware and thermal behavior all matter.")
    12 -> note("NVMe-oF", "NVMe over Fabrics extends the NVMe command model to remote storage. Major transports are NVMe/TCP, NVMe/RDMA and NVMe/FC.", "Trace application → filesystem/block layer → NVMe initiator → fabric → target → media. Failure domains include discovery, routing, MTU, queueing and target availability.", "STORAGE-ADMIN CONNECTION: SAN initiator/target thinking transfers well, but NVMe-oF changes the protocol stack and performance expectations.")
    13 -> note("RDMA", "RDMA enables direct memory-to-memory data movement with reduced CPU involvement. Know HCA/NIC, queue pair, completion queue, memory registration and work request conceptually.", "RDMA is a data-movement model; InfiniBand and RoCE are fabrics/transports that can carry RDMA.", "TROUBLESHOOTING: verify device discovery, link/fabric state, counters, MTU and application errors before declaring RDMA broken.")
    14 -> note("INFINIBAND AND ROCE", "InfiniBand is purpose-built for high-performance interconnects. RoCE carries RDMA over Ethernet and therefore adds Ethernet congestion and loss-management considerations.", "Learn HCA, leaf/spine or fat-tree topology, QoS, virtual lanes, PFC, ECN, routing and congestion.", "INTERVIEW: compare InfiniBand and RoCE using architecture, operations, congestion behavior, ecosystem and workload requirements—not only speed.")
    15 -> note("THE COMPLETE HPC/AI DATA PATH", "Training is a loop: dataset access → preprocessing → host memory → GPU memory → compute → collective synchronization → checkpoint.", "Storage may be shared parallel storage or local NVMe scratch/cache. If data movement cannot feed accelerators, theoretical FLOPS are wasted.", "CAPSTONE: build a troubleshooting tree covering storage throughput, metadata, fabric congestion, CPU preprocessing, GPU memory, NCCL communication and batching.")
    16 -> note("LINUX FOR HPC", "Learn processes, services, filesystems, devices, permissions, networking and logs as one operating-system model. Know /proc, /sys, udev, systemd and kernel messages at a practical level.", "Useful tools: lsblk, lsscsi, findmnt, df, du, mount, ps, top, free, vmstat, iostat, ip, ss, ethtool, dmesg and journalctl.", "FIELD RULE: collect timestamps, symptoms and evidence before changing configuration.")
    17 -> note("LINUX FILESYSTEMS", "Distinguish block devices, partitions, filesystems and mounts. Learn inode, directory entry, permissions, links and mount options.", "Understand that a filesystem can have free capacity but no free inodes. POSIX filesystems are abstractions over very different storage architectures.", "HPC CONNECTION: an application sees a namespace while underneath may be many servers, network paths and storage targets.")
    18 -> note("PROCESSES AND I/O", "A process has an address space, file descriptors, threads and scheduling state. I/O-heavy processes may spend time waiting rather than consuming CPU.", "Use ps, top, pidstat, lsof and /proc/<pid> to inspect behavior.", "EXERCISE: run an FIO test and observe process state, CPU, memory and disk statistics together.")
    19 -> note("MEMORY", "Know RAM, page cache, buffers, virtual memory, swap and memory pressure. Linux using RAM for cache is normal.", "Caching can distort benchmarks. Repeated reads of a small dataset may measure memory/cache instead of backend storage.", "TOOLS: free -h, vmstat, /proc/meminfo and sar. Distinguish capacity pressure, reclaim and actual swapping.")
    20 -> note("PERMISSIONS AND IDENTITY", "Know user/group IDs, mode bits, ownership and ACLs. Shared HPC environments require consistent identity mapping.", "NFS and parallel filesystems can expose identity and policy differences; containers add another identity layer.", "TROUBLESHOOTING: separate permission denied, path unavailable, mount failure and read-only filesystem before changing permissions.")
    21 -> note("LINUX NETWORKING", "Know interface, MAC, IP, subnet, gateway, route, DNS, TCP/UDP, MTU and sockets. HPC adds VLAN/VRF, multiple NICs, bonding and RDMA devices.", "Tools: ip addr, ip route, ping, traceroute where appropriate, ss, ethtool and tcpdump at a basic level.", "STORAGE CONNECTION: NFS failures may be DNS/routing issues; slow storage can be a network bottleneck; RDMA requires different diagnostics.")
    22 -> note("LOGS AND EVIDENCE", "Logs provide the incident timeline. Learn journalctl, dmesg, kernel messages and service logs.", "Storage failures can appear as I/O errors, path resets, link flaps, filesystem errors or application timeouts. Correlate client and server timestamps.", "FIELD RULE: preserve the original error rather than reducing every symptom to ‘storage issue’.")
    23 -> note("BASH BASICS", "Learn variables, quoting, command substitution, pipes, redirection, exit codes, grep, awk, sed, sort, uniq and loops.", "Operational scripts should validate input, handle failures, log useful output and avoid destructive defaults. Understand $? and safe quoting.", "LAB: check disk usage on test hosts and generate a report. Automate production changes only after the checks are proven safe.")
    24 -> note("BASH AUTOMATION", "Move from one-liners to functions, arguments, configuration, logging, retries and controlled concurrency. Learn idempotence.", "Useful targets include health checks, mount validation, performance collection, inventory and benchmark orchestration.", "INTERVIEW: design a check for 100 Linux nodes that distinguishes unreachable hosts from hosts with unhealthy storage.")
    25 -> note("PYTHON FOR INFRASTRUCTURE", "Learn variables, lists/dicts, functions, modules, exceptions, files, JSON, subprocess and HTTP/API basics.", "Python is useful for parsing command output, generating reports, calling REST APIs, collecting metrics and orchestrating repetitive tasks.", "PROJECT: read JSON inventory, validate fields, run a safe check and create a Markdown or CSV report.")
    26 -> note("BLOCK, FILE AND OBJECT", "Block exposes a device-like abstraction; file storage exposes a shared namespace; object storage exposes API-addressed objects and metadata.", "Know FC, iSCSI and NVMe-oF as block-oriented technologies; NFS, Lustre and Storage Scale as file examples; S3 as an object API.", "ARCHITECTURE QUESTION: select the interface from workload semantics and access pattern, not brand familiarity.")
    27 -> note("NFS", "Learn exports, mounts, NFS versions, RPC, client/server roles, UID/GID, permissions, mount options and network dependencies.", "Understand the difference between NFS availability, latency and throughput. Server, network and client tuning can all matter.", "TROUBLESHOOT: validate DNS, routes, ports, exports, mount state, permissions and server health in that order.")
    28 -> note("S3 AND OBJECT STORAGE", "Object storage uses buckets, objects, keys and metadata rather than a traditional POSIX directory hierarchy.", "Learn PUT, GET, LIST, DELETE, multipart upload, consistency concepts, lifecycle and versioning. Cloudian HyperStore is an S3-compatible enterprise example.", "AI CONNECTION: object storage is common for datasets, artifacts and archival tiers; applications may need a filesystem/cache layer for training workloads.")
    29 -> note("RAID AND DATA PROTECTION", "Understand mirroring, striping and parity. RAID improves availability/performance characteristics but is not the same as backup.", "Know rebuild cost, degraded mode, hot spots and the trade-off between capacity, fault tolerance and write overhead.", "INTERVIEW: explain why a healthy RAID group can still suffer from controller, fabric, filesystem or application-level failure.")
    30 -> note("STORAGE PERFORMANCE METRICS", "Know IOPS, throughput, latency, bandwidth, queue depth, concurrency and utilization. Always attach units and workload conditions.", "Latency distributions matter; averages can hide tail latency. Measure client-side and backend-side views when possible.", "FIELD RULE: performance is a system property, not an array specification alone.")
    31 -> note("FIO", "FIO is a flexible storage benchmark. Learn rw patterns, block size, iodepth, numjobs, direct I/O, runtime, size and output interpretation.", "Build controlled tests for sequential/random reads/writes and vary concurrency deliberately. Avoid confusing cached results with backend results.", "LAB: change one variable at a time and record IOPS, bandwidth and latency.")
    32 -> note("QUEUE DEPTH AND CONCURRENCY", "Queue depth represents outstanding I/O. numjobs represents concurrent workers in FIO. More concurrency can expose parallelism but eventually causes contention.", "Plot performance as concurrency rises. Look for the knee where latency increases faster than useful throughput.", "INTERVIEW: explain why maximum IOPS at extreme queue depth may be irrelevant to an AI training workload.")
    33 -> note("LATENCY", "Latency is time spent completing an operation. Break it into application, filesystem, host, network, target and media components where possible.", "Study average and percentile latency such as p95 and p99. Tail latency can affect synchronized distributed jobs disproportionately.", "FIELD RULE: identify where latency is introduced instead of treating the entire path as one number.")
    34 -> note("THROUGHPUT", "Throughput is amount of data transferred per unit time. It depends on block size, concurrency, network bandwidth, filesystem layout and storage backend.", "Aggregate bandwidth can be much higher than one-client bandwidth in a parallel filesystem.", "EXERCISE: estimate whether a dataset can feed a multi-GPU job fast enough and identify the bottleneck if not.")
    35 -> note("HPC STORAGE ARCHITECTURE", "A typical design may combine compute nodes, local NVMe, parallel filesystem, object/archive tiers and a high-speed fabric.", "Map clients, metadata, data targets, network paths, caches and failure domains. Vendor examples include DDN, Dell, IBM, WEKA, VAST and Pure/Everpure.", "ARCHITECTURE: design for throughput, metadata rate, capacity, resilience, recovery and workload concurrency together.")
    36 -> note("LUSTRE", "Learn clients, MDS/MDT, OSS/OST, namespace and striping. Lustre separates metadata operations from bulk data movement to scale parallel I/O.", "Understand mounts, targets, stripes, recovery and the difference between metadata bottlenecks and data-bandwidth bottlenecks.", "LAB: create a small Lustre environment or study a real deployment diagram and explain the path of a file create versus a large read.")
    37 -> note("METADATA", "Metadata includes names, ownership, permissions, timestamps, directory structure and file-location information. Metadata workloads can be very different from bulk reads/writes.", "Millions of small files can stress metadata services even when total capacity is low. Application design and namespace layout matter.", "INTERVIEW: distinguish metadata IOPS from data throughput and explain why one does not predict the other.")
    38 -> note("STRIPING AND PARALLEL I/O", "Striping distributes file data across multiple storage targets so many clients or threads can transfer data concurrently.", "Stripe width and size must match workload. Too little parallelism can bottleneck; excessive striping can create overhead and contention.", "EXERCISE: reason about how a large sequential training dataset should be distributed across targets.")
    39 -> note("IBM STORAGE SCALE / GPFS", "Storage Scale is a parallel filesystem and data platform descended from GPFS. Learn shared namespace, nodes, filesets, policies and distributed metadata conceptually.", "Compare its architecture and operational model with Lustre without assuming they use the same terminology or components.", "CAREER VALUE: GPFS/Storage Scale experience is directly relevant to enterprise HPC and AI infrastructure.")
    40 -> note("CEPH", "Ceph is distributed software-defined storage with RADOS underneath and block (RBD), object (RGW/S3) and file (CephFS) interfaces above it.", "Learn MON, MGR, OSD, pools, PGs, CRUSH, replication and erasure coding. Recovery traffic itself consumes network and storage resources.", "FIELD RULE: understand data placement and failure recovery before tuning performance.")
    41 -> note("FABRIC TROUBLESHOOTING", "Troubleshoot the path layer by layer: physical link, adapter, switch port, routing, MTU, QoS/congestion and application traffic.", "For Ethernet/RoCE consider PFC/ECN and counters; for InfiniBand understand fabric management, port state and topology tools.", "METHOD: compare a healthy path with a failing path and identify the first metric that diverges.")
    42 -> note("AI STORAGE PIPELINE", "AI data movement commonly includes object/data lake → preprocessing → cache/local NVMe → shared filesystem → GPU memory → checkpoint → artifact/archive.", "Training emphasizes sustained reads and checkpoint bursts; inference may emphasize predictable latency and concurrent requests.", "DESIGN QUESTION: choose storage tiers by access pattern, capacity, latency, bandwidth and recovery requirements.")
    43 -> note("NVMe DEEP DIVE", "Go deeper into PCIe topology, namespaces, queue pairs, submission/completion queues, firmware and health telemetry.", "Compare local NVMe with networked NVMe. Local media can provide low latency but does not automatically provide shared namespace or centralized resilience.", "INTERVIEW: explain when local NVMe cache is preferable to remote shared storage and when it is not.")
    44 -> note("GPUDIRECT STORAGE", "GPUDirect Storage is designed to move data between storage and GPU memory with a path that can reduce unnecessary CPU/memory copies when supported by the platform.", "The complete result depends on GPU, driver, filesystem/storage, NIC/fabric and application support. It is not simply a switch you turn on.", "AI CONNECTION: reducing data-movement overhead can help keep accelerators supplied during high-throughput workloads.")
    45 -> note("CAPSTONE — THINK LIKE AN HPC/AI STORAGE ENGINEER", "Combine Linux, storage, filesystems, networking, RDMA, performance testing, automation and AI workload knowledge into one troubleshooting model.", "Given a slow training job, establish workload, measure client behavior, inspect CPU/memory, filesystem metadata/data paths, network/fabric, storage targets and GPU utilization.", "FINAL TEST: draw the full architecture, explain every hop, propose measurements, identify likely bottlenecks and describe a safe validation plan. This is the standard to aim for before interviewing for HPC/AI infrastructure roles.")
    else -> ""
}

private fun note(title: String, body: String, detail: String, field: String): String = """
DEEP DIVE — $title

$body

$detail

$field
""".trimIndent()
